// LifeTrack/frontend/src/app/pages/login/login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { finalize } from 'rxjs';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  login: string = '';
  senha: string = '';
  error: string = '';
  loading: boolean = false;

  private authService = inject(AuthService);
  private router = inject(Router);

  handleSubmit() {
    this.error = '';
    this.loading = true;

    this.authService.login({ login: this.login, senha: this.senha }).pipe(
      finalize(() => {
        this.loading = false;
      })
    ).subscribe({
      next: (res) => {
        const user = this.authService.getUsuarioLogado() ?? res.user;
        if (user?.role === 'ADMIN' || user?.perfil === 'ADMIN') {
          this.router.navigate(['/admin']);
        } else {
          this.router.navigate(['/operador']);
        }
      },
      error: (err) => {
        this.error = err.error?.message || err.message || 'Erro ao fazer login. Verifique suas credenciais.';
      }
    });
  }
}

<div class="login-container">
  <div class="login-box">
    <div class="login-header">
      <h1>🚑 LifeTrack</h1>
      <p>Sistema de Gestão de Emergências</p>
    </div>
    
    <form (ngSubmit)="handleSubmit()" #loginForm="ngForm" class="login-form">
      <div *ngIf="error" class="error-message">{{ error }}</div>
      
      <div class="form-group">
        <label for="login">Usuário</label>
        <input
          id="login"
          name="login"
          type="text"
          [(ngModel)]="login"
          placeholder="Digite seu usuário"
          required
          autofocus
        />
      </div>

      <div class="form-group">
        <label for="senha">Senha</label>
        <input
          id="senha"
          name="senha"
          type="password"
          [(ngModel)]="senha"
          placeholder="Digite sua senha"
          required
        />
      </div>

      <button 
        type="submit" 
        class="login-button"
        [disabled]="loading || loginForm.invalid"
      >
        {{ loading ? 'Entrando...' : 'Entrar' }}
      </button>
    </form>
  </div>
</div>

// LifeTrack/frontend/src/pages/Login.jsx
import { useState } from 'react';
import { authService } from '../services/authService';
import './Login.css';

function Login({ onLoginSuccess }) {
  const [login, setLogin] = useState('');
  const [senha, setSenha] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      await authService.login(login, senha);
      onLoginSuccess();
    } catch (err) {
      setError(err.message || 'Erro ao fazer login. Verifique suas credenciais.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-container">
      <div className="login-box">
        <div className="login-header">
          <h1>🚑 LifeTrack</h1>
          <p>Sistema de Gestão de Emergências</p>
        </div>
        
        <form onSubmit={handleSubmit} className="login-form">
          {error && <div className="error-message">{error}</div>}
          
          <div className="form-group">
            <label htmlFor="login">Usuário</label>
            <input
              id="login"
              type="text"
              value={login}
              onChange={(e) => setLogin(e.target.value)}
              placeholder="Digite seu usuário"
              required
              autoFocus
            />
          </div>

          <div className="form-group">
            <label htmlFor="senha">Senha</label>
            <input
              id="senha"
              type="password"
              value={senha}
              onChange={(e) => setSenha(e.target.value)}
              placeholder="Digite sua senha"
              required
            />
          </div>

          <button 
            type="submit" 
            className="login-button"
            disabled={loading}
          >
            {loading ? 'Entrando...' : 'Entrar'}
          </button>
        </form>
      </div>
    </div>
  );
}

export default Login;
