// LifeTrack/frontend-angular/src/app/pages/operador/listar-ocorrencias/listar-ocorrencias.component.ts
import { Component, OnInit, OnDestroy, inject } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subscription, interval } from 'rxjs';
import { OcorrenciaService } from '../../../core/services/ocorrencia.service';
import { SlaTimerComponent } from '../../../shared/components/sla-timer/sla-timer.component';
import { HistoricoOcorrenciaComponent } from '../../../shared/components/historico-ocorrencia/historico-ocorrencia.component';
import { SugerirAmbulanciasComponent } from '../sugerir-ambulancias/sugerir-ambulancias.component';

@Component({
  selector: 'app-listar-ocorrencias',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    SlaTimerComponent,
    HistoricoOcorrenciaComponent,
    SugerirAmbulanciasComponent
  ],
  providers: [DatePipe],
  templateUrl: './listar-ocorrencias.component.html',
  styleUrls: ['./listar-ocorrencias.component.css']
})
export class ListarOcorrenciasComponent implements OnInit, OnDestroy {
  ocorrencias: any[] = [];
  loading = true;
  error = '';
  filtroStatus = 'TODAS';
  filtroGravidade = 'TODAS';
  busca = '';
  despachando: number | null = null;
  mostrarSugestoes: number | null = null;

  private ocorrenciaService = inject(OcorrenciaService);
  private datePipe = inject(DatePipe);
  private refreshSubscription?: Subscription;

  ngOnInit() {
    this.carregarOcorrencias();
    this.refreshSubscription = interval(5000).subscribe(() => this.carregarOcorrencias());
  }

  ngOnDestroy() {
    this.refreshSubscription?.unsubscribe();
  }

  carregarOcorrencias() {
    this.ocorrenciaService.listar().subscribe({
      next: (dados) => {
        this.ocorrencias = dados;
        this.error = '';
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Erro ao carregar ocorrências: ' + (err.message || err);
        this.loading = false;
      }
    });
  }

  get ocorrenciasFiltradas(): any[] {
    return this.ocorrencias.filter(oc => {
      const matchStatus = this.filtroStatus === 'TODAS' || oc.status === this.filtroStatus;
      const matchGravidade = this.filtroGravidade === 'TODAS' || oc.gravidade === this.filtroGravidade;
      const matchBusca = !this.busca ||
        oc.tipoOcorrencia?.toLowerCase().includes(this.busca.toLowerCase()) ||
        oc.bairroLocal?.nome?.toLowerCase().includes(this.busca.toLowerCase());
      return matchStatus && matchGravidade && matchBusca;
    });
  }

  handleDespachar(id: number) {
    if (!window.confirm('Deseja realmente despachar esta ocorrência?')) return;
    this.despachando = id;
    this.error = '';
    this.ocorrenciaService.despachar(id).subscribe({
      next: () => {
        alert('Ocorrência despachada com sucesso!');
        this.carregarOcorrencias();
      },
      error: (err) => {
        this.error = 'Erro ao despachar: ' + (err.error?.message || err.message);
        alert('Erro ao despachar: ' + (err.error?.message || err.message));
      },
      complete: () => (this.despachando = null)
    });
  }

  onDespacharAposSugestao() {
    this.mostrarSugestoes = null;
    this.carregarOcorrencias();
  }

  formatarData(data: any): string {
    return this.datePipe.transform(data, 'dd/MM/yyyy HH:mm') || '-';
  }

  getStatusConfig(status: string): { bg: string; color: string; text: string } {
    const map: Record<string, { bg: string; color: string; text: string }> = {
      ABERTA:         { bg: '#d1fae5', color: '#065f46', text: '🟢 ABERTA' },
      DESPACHADA:     { bg: '#dbeafe', color: '#1e40af', text: '🔵 DESPACHADA' },
      EM_ATENDIMENTO: { bg: '#fef3c7', color: '#92400e', text: '🟡 EM ATENDIMENTO' },
      CONCLUIDA:      { bg: '#e0e7ff', color: '#3730a3', text: '✅ CONCLUÍDA' },
      CANCELADA:      { bg: '#fee2e2', color: '#991b1b', text: '🔴 CANCELADA' }
    };
    return map[status] || { bg: '#f3f4f6', color: '#374151', text: status };
  }

  getGravidadeConfig(gravidade: string): { bg: string; color: string } {
    const map: Record<string, { bg: string; color: string }> = {
      BAIXA: { bg: '#d1fae5', color: '#065f46' },
      MEDIA: { bg: '#fef3c7', color: '#92400e' },
      ALTA:  { bg: '#fee2e2', color: '#dc2626' }
    };
    return map[gravidade] || { bg: '#f3f4f6', color: '#374151' };
  }

  showSlaTimer(status: string): boolean {
    return ['ABERTA', 'DESPACHADA', 'EM_ATENDIMENTO', 'CONCLUIDA'].includes(status);
  }

  showHistorico(status: string): boolean {
    return ['DESPACHADA', 'EM_ATENDIMENTO', 'CONCLUIDA'].includes(status);
  }
}

<div class="listar-page">
  <div class="page-header">
    <h1 class="page-title">Ocorrências Registradas</h1>
    <button class="btn btn-primary" (click)="carregarOcorrencias()">🔄 Atualizar</button>
  </div>

  <div *ngIf="error" class="alert alert-error">{{ error }}</div>

  <!-- Filtros -->
  <div class="filtros-card">
    <div class="filtros-grid">
      <div class="form-group">
        <label class="form-label">Status</label>
        <select class="form-select" [(ngModel)]="filtroStatus">
          <option value="TODAS">Todas</option>
          <option value="ABERTA">Abertas</option>
          <option value="DESPACHADA">Despachadas</option>
          <option value="EM_ATENDIMENTO">Em Atendimento</option>
          <option value="CONCLUIDA">Concluídas</option>
          <option value="CANCELADA">Canceladas</option>
        </select>
      </div>
      <div class="form-group">
        <label class="form-label">Gravidade</label>
        <select class="form-select" [(ngModel)]="filtroGravidade">
          <option value="TODAS">Todas</option>
          <option value="BAIXA">Baixa</option>
          <option value="MEDIA">Média</option>
          <option value="ALTA">Alta</option>
        </select>
      </div>
      <div class="form-group">
        <label class="form-label">Buscar</label>
        <input type="text" class="form-input" [(ngModel)]="busca" placeholder="Buscar por tipo ou bairro..." />
      </div>
    </div>
  </div>

  <!-- Loading -->
  <div *ngIf="loading" class="state-box">Carregando ocorrências...</div>

  <!-- Empty -->
  <div *ngIf="!loading && ocorrenciasFiltradas.length === 0" class="state-box">
    Nenhuma ocorrência encontrada.
  </div>

  <!-- Tabela -->
  <div *ngIf="!loading && ocorrenciasFiltradas.length > 0" class="table-card">
    <div class="table-wrapper">
      <table class="ocorrencias-table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Data/Hora</th>
            <th>Bairro</th>
            <th>Tipo</th>
            <th>Gravidade</th>
            <th>Status</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody>
          <ng-container *ngFor="let oc of ocorrenciasFiltradas">
            <!-- Linha principal -->
            <tr>
              <td class="text-muted">#{{ oc.id }}</td>
              <td>{{ formatarData(oc.dataHoraAbertura) }}</td>
              <td>{{ oc.bairroLocal?.nome || '-' }}</td>
              <td>{{ oc.tipoOcorrencia }}</td>
              <td>
                <span class="badge"
                  [style.backgroundColor]="getGravidadeConfig(oc.gravidade).bg"
                  [style.color]="getGravidadeConfig(oc.gravidade).color">
                  {{ oc.gravidade }}
                </span>
              </td>
              <td>
                <span class="badge"
                  [style.backgroundColor]="getStatusConfig(oc.status).bg"
                  [style.color]="getStatusConfig(oc.status).color">
                  {{ getStatusConfig(oc.status).text }}
                </span>
              </td>
              <td>
                <div *ngIf="oc.status === 'ABERTA'" class="actions-cell">
                  <button class="btn btn-sm btn-primary" (click)="mostrarSugestoes = oc.id">
                    🔍 Ver Sugestões
                  </button>
                  <button class="btn btn-sm btn-success"
                    [disabled]="despachando === oc.id"
                    (click)="handleDespachar(oc.id)">
                    {{ despachando === oc.id ? 'Despachando...' : '🚑 Despachar' }}
                  </button>
                </div>
              </td>
            </tr>

            <!-- SLA Timer -->
            <tr *ngIf="showSlaTimer(oc.status)">
              <td colspan="7" class="sub-row">
                <app-sla-timer [ocorrenciaId]="oc.id" [status]="oc.status"></app-sla-timer>
              </td>
            </tr>

            <!-- Histórico -->
            <tr *ngIf="showHistorico(oc.status)">
              <td colspan="7" class="sub-row">
                <app-historico-ocorrencia
                  [ocorrenciaId]="oc.id"
                  [atualizarEmTempoReal]="oc.status !== 'CONCLUIDA'">
                </app-historico-ocorrencia>
              </td>
            </tr>
          </ng-container>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- Modal Sugestões -->
<app-sugerir-ambulancias
  *ngIf="mostrarSugestoes"
  [ocorrenciaId]="mostrarSugestoes"
  (despachar)="onDespacharAposSugestao()"
  (fechar)="mostrarSugestoes = null">
</app-sugerir-ambulancias>

// LifeTrack/frontend/src/pages/operador/sections/ListarOcorrencias.jsx
import { useState, useEffect } from 'react';
import { ocorrenciaService } from '../../../services/ocorrenciaService';
import SugerirAmbulancias from './SugerirAmbulancias';
import '../OperatorLayout.css';

function ListarOcorrencias() {
  const [ocorrencias, setOcorrencias] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [filtroStatus, setFiltroStatus] = useState('TODAS');
  const [filtroGravidade, setFiltroGravidade] = useState('TODAS');
  const [busca, setBusca] = useState('');
  const [despachando, setDespachando] = useState(null);
  const [mostrarSugestoes, setMostrarSugestoes] = useState(null);

  useEffect(() => {
    carregarOcorrencias();
  }, []);

  const carregarOcorrencias = async () => {
    try {
      setLoading(true);
      const dados = await ocorrenciaService.listar();
      setOcorrencias(dados);
      setError('');
    } catch (err) {
      setError('Erro ao carregar ocorrências: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleDespachar = async (id) => {
    if (!window.confirm('Deseja realmente despachar esta ocorrência?')) {
      return;
    }

    try {
      setDespachando(id);
      setError('');
      await ocorrenciaService.despachar(id);
      await carregarOcorrencias();
      alert('Ocorrência despachada com sucesso!');
    } catch (err) {
      setError('Erro ao despachar ocorrência: ' + err.message);
      alert('Erro ao despachar: ' + err.message);
    } finally {
      setDespachando(null);
    }
  };

  const handleDespacharAposSugestao = async () => {
    await carregarOcorrencias();
  };

  const formatarData = (data) => {
    if (!data) return '-';
    const date = new Date(data);
    return date.toLocaleString('pt-BR');
  };

  const getStatusBadge = (status) => {
    const badges = {
      'ABERTA': { bg: '#d1fae5', color: '#065f46', text: '🟢 ABERTA' },
      'DESPACHADA': { bg: '#dbeafe', color: '#1e40af', text: '🔵 DESPACHADA' },
      'EM_ATENDIMENTO': { bg: '#fef3c7', color: '#92400e', text: '🟡 EM ATENDIMENTO' },
      'CONCLUIDA': { bg: '#e0e7ff', color: '#3730a3', text: '✅ CONCLUÍDA' },
      'CANCELADA': { bg: '#fee2e2', color: '#991b1b', text: '🔴 CANCELADA' }
    };
    const badge = badges[status] || { bg: '#f3f4f6', color: '#374151', text: status };
    return (
      <span style={{
        padding: '4px 12px',
        borderRadius: '12px',
        fontSize: '0.875rem',
        fontWeight: '600',
        backgroundColor: badge.bg,
        color: badge.color
      }}>
        {badge.text}
      </span>
    );
  };

  const getGravidadeBadge = (gravidade) => {
    const badges = {
      'BAIXA': { bg: '#d1fae5', color: '#065f46' },
      'MEDIA': { bg: '#fef3c7', color: '#92400e' },
      'ALTA': { bg: '#fee2e2', color: '#dc2626' }
    };
    const badge = badges[gravidade] || { bg: '#f3f4f6', color: '#374151' };
    return (
      <span style={{
        padding: '4px 12px',
        borderRadius: '12px',
        fontSize: '0.875rem',
        fontWeight: '600',
        backgroundColor: badge.bg,
        color: badge.color
      }}>
        {gravidade}
      </span>
    );
  };

  const ocorrenciasFiltradas = ocorrencias.filter(oc => {
    const matchStatus = filtroStatus === 'TODAS' || oc.status === filtroStatus;
    const matchGravidade = filtroGravidade === 'TODAS' || oc.gravidade === filtroGravidade;
    const matchBusca = !busca || 
      (oc.tipoOcorrencia && oc.tipoOcorrencia.toLowerCase().includes(busca.toLowerCase())) ||
      (oc.bairroLocal && oc.bairroLocal.nome && oc.bairroLocal.nome.toLowerCase().includes(busca.toLowerCase()));
    return matchStatus && matchGravidade && matchBusca;
  });

  return (
    <div>
      <div style={{ marginBottom: '32px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h1 style={{ color: '#1f2937', fontSize: '2rem', margin: 0 }}>
          Ocorrências Registradas
        </h1>
        <button
          onClick={carregarOcorrencias}
          style={{
            padding: '10px 20px',
            backgroundColor: '#2563eb',
            color: 'white',
            border: 'none',
            borderRadius: '8px',
            fontSize: '0.95rem',
            fontWeight: '600',
            cursor: 'pointer'
          }}
        >
          🔄 Atualizar
        </button>
      </div>

      {error && (
        <div style={{
          padding: '12px 16px',
          backgroundColor: '#fee2e2',
          color: '#dc2626',
          borderRadius: '8px',
          marginBottom: '24px'
        }}>
          {error}
        </div>
      )}

      <div style={{
        backgroundColor: 'white',
        padding: '24px',
        borderRadius: '12px',
        boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
        marginBottom: '24px'
      }}>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 2fr', gap: '16px' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '8px', fontWeight: '600', color: '#374151' }}>
              Status
            </label>
            <select
              value={filtroStatus}
              onChange={(e) => setFiltroStatus(e.target.value)}
              style={{
                width: '100%',
                padding: '10px',
                border: '1px solid #d1d5db',
                borderRadius: '8px'
              }}
            >
              <option value="TODAS">Todas</option>
              <option value="ABERTA">Abertas</option>
              <option value="DESPACHADA">Despachadas</option>
              <option value="EM_ATENDIMENTO">Em Atendimento</option>
              <option value="CONCLUIDA">Concluídas</option>
              <option value="CANCELADA">Canceladas</option>
            </select>
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '8px', fontWeight: '600', color: '#374151' }}>
              Gravidade
            </label>
            <select
              value={filtroGravidade}
              onChange={(e) => setFiltroGravidade(e.target.value)}
              style={{
                width: '100%',
                padding: '10px',
                border: '1px solid #d1d5db',
                borderRadius: '8px'
              }}
            >
              <option value="TODAS">Todas</option>
              <option value="BAIXA">Baixa</option>
              <option value="MEDIA">Média</option>
              <option value="ALTA">Alta</option>
            </select>
          </div>
          <div>
            <label style={{ display: 'block', marginBottom: '8px', fontWeight: '600', color: '#374151' }}>
              Buscar
            </label>
            <input
              type="text"
              value={busca}
              onChange={(e) => setBusca(e.target.value)}
              placeholder="Buscar por tipo ou bairro..."
              style={{
                width: '100%',
                padding: '10px',
                border: '1px solid #d1d5db',
                borderRadius: '8px'
              }}
            />
          </div>
        </div>
      </div>

      {loading ? (
        <div style={{ textAlign: 'center', padding: '40px', color: '#6b7280' }}>
          Carregando ocorrências...
        </div>
      ) : ocorrenciasFiltradas.length === 0 ? (
        <div style={{
          backgroundColor: 'white',
          padding: '40px',
          borderRadius: '12px',
          textAlign: 'center',
          color: '#6b7280'
        }}>
          Nenhuma ocorrência encontrada.
        </div>
      ) : (
        <div style={{
          backgroundColor: 'white',
          borderRadius: '12px',
          boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
          overflow: 'hidden'
        }}>
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
              <thead>
                <tr style={{ backgroundColor: '#f9fafb', borderBottom: '2px solid #e5e7eb' }}>
                  <th style={{ padding: '16px', textAlign: 'left', fontWeight: '600', color: '#374151' }}>ID</th>
                  <th style={{ padding: '16px', textAlign: 'left', fontWeight: '600', color: '#374151' }}>Data/Hora</th>
                  <th style={{ padding: '16px', textAlign: 'left', fontWeight: '600', color: '#374151' }}>Bairro</th>
                  <th style={{ padding: '16px', textAlign: 'left', fontWeight: '600', color: '#374151' }}>Tipo</th>
                  <th style={{ padding: '16px', textAlign: 'left', fontWeight: '600', color: '#374151' }}>Gravidade</th>
                  <th style={{ padding: '16px', textAlign: 'left', fontWeight: '600', color: '#374151' }}>Status</th>
                  <th style={{ padding: '16px', textAlign: 'left', fontWeight: '600', color: '#374151' }}>Ações</th>
                </tr>
              </thead>
              <tbody>
                {ocorrenciasFiltradas.map(oc => (
                  <tr key={oc.id} style={{ borderBottom: '1px solid #e5e7eb' }}>
                    <td style={{ padding: '16px', color: '#6b7280' }}>#{oc.id}</td>
                    <td style={{ padding: '16px', color: '#374151' }}>{formatarData(oc.dataHoraAbertura)}</td>
                    <td style={{ padding: '16px', color: '#374151' }}>
                      {oc.bairroLocal ? oc.bairroLocal.nome : '-'}
                    </td>
                    <td style={{ padding: '16px', color: '#374151' }}>{oc.tipoOcorrencia}</td>
                    <td style={{ padding: '16px' }}>{getGravidadeBadge(oc.gravidade)}</td>
                    <td style={{ padding: '16px' }}>{getStatusBadge(oc.status)}</td>
                    <td style={{ padding: '16px' }}>
                      {oc.status === 'ABERTA' && (
                        <div style={{ display: 'flex', gap: '8px' }}>
                          <button
                            onClick={() => setMostrarSugestoes(oc.id)}
                            style={{
                              padding: '8px 16px',
                              backgroundColor: '#2563eb',
                              color: 'white',
                              border: 'none',
                              borderRadius: '6px',
                              fontSize: '0.875rem',
                              fontWeight: '600',
                              cursor: 'pointer'
                            }}
                          >
                            🔍 Ver Sugestões
                          </button>
                          <button
                            onClick={() => handleDespachar(oc.id)}
                            disabled={despachando === oc.id}
                            style={{
                              padding: '8px 16px',
                              backgroundColor: '#10b981',
                              color: 'white',
                              border: 'none',
                              borderRadius: '6px',
                              fontSize: '0.875rem',
                              fontWeight: '600',
                              cursor: despachando === oc.id ? 'not-allowed' : 'pointer',
                              opacity: despachando === oc.id ? 0.6 : 1
                            }}
                          >
                            {despachando === oc.id ? 'Despachando...' : '🚑 Despachar'}
                          </button>
                        </div>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {mostrarSugestoes && (
        <SugerirAmbulancias
          ocorrenciaId={mostrarSugestoes}
          onDespachar={handleDespacharAposSugestao}
          onClose={() => setMostrarSugestoes(null)}
        />
      )}
    </div>
  );
}

export default ListarOcorrencias;
