// LifeTrack/frontend/src/app/pages/admin/gerenciar-ambulancias/gerenciar-ambulancias.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { AmbulanciaService } from '../../../core/services/ambulancia.service';
import { BairroService } from '../../../core/services/bairro.service';
import { AnaliseEstrategicaService } from '../../../core/services/analise-estrategica.service';
import { AutocompleteSelectComponent } from '../../../shared/components/autocomplete-select/autocomplete-select.component';

@Component({
  selector: 'app-gerenciar-ambulancias',
  standalone: true,
  imports: [CommonModule, FormsModule, AutocompleteSelectComponent],
  templateUrl: './gerenciar-ambulancias.component.html',
  styleUrls: ['../admin.shared.css']
})
export class GerenciarAmbulanciasComponent implements OnInit {
  ambulancias: any[] = [];
  bairros: any[] = [];
  bairrosSugeridos: any[] = [];
  loading = true;
  loadingSugestoes = false;
  error = '';
  showModal = false;
  formData = { placa: '', tipo: 'BASICA', idBairroBase: '' as any };

  private ambulanciaService = inject(AmbulanciaService);
  private bairroService = inject(BairroService);
  private analiseService = inject(AnaliseEstrategicaService);

  getOptionLabelBairro = (opt: any) => opt?.nome ?? opt;
  getOptionValueBairro = (opt: any) => opt?.id?.toString() ?? opt;

  ngOnInit() {
    forkJoin({
      ambulancias: this.ambulanciaService.listar(),
      bairros: this.bairroService.listar()
    }).subscribe({
      next: ({ ambulancias, bairros }) => {
        this.ambulancias = ambulancias;
        this.bairros = bairros;
        this.loading = false;
      },
      error: (e) => { this.error = 'Erro ao carregar dados: ' + (e.message || e); this.loading = false; }
    });
  }

  openModal() {
    this.formData = { placa: '', tipo: 'BASICA', idBairroBase: '' };
    this.bairrosSugeridos = [];
    this.showModal = true;
    this.carregarSugestoes('BASICA');
  }

  closeModal() { this.showModal = false; this.bairrosSugeridos = []; }

  onTipoChange(tipo: string) {
    this.formData.tipo = tipo;
    this.formData.idBairroBase = '';
    this.carregarSugestoes(tipo);
  }

  private carregarSugestoes(tipo: string) {
    this.loadingSugestoes = true;
    this.analiseService.obterBairrosSugeridos(tipo).subscribe({
      next: (sugestoes) => { this.bairrosSugeridos = sugestoes.slice(0, 5); this.loadingSugestoes = false; },
      error: () => { this.bairrosSugeridos = []; this.loadingSugestoes = false; }
    });
  }

  selecionarSugestao(id: number) {
    this.formData.idBairroBase = id.toString();
  }

  handleSubmit() {
    this.error = '';
    if (!this.formData.idBairroBase) { this.error = 'Selecione um bairro base'; return; }
    const payload = { placa: this.formData.placa.trim(), tipo: this.formData.tipo, idBairroBase: parseInt(this.formData.idBairroBase) };
    this.ambulanciaService.cadastrar(payload).subscribe({
      next: () => { this.closeModal(); this.recarregarAmbulancias(); },
      error: (e) => { this.error = 'Erro ao salvar: ' + (e.error?.message || e.message); }
    });
  }

  toggleStatus(id: number, ativa: boolean) {
    const obs = ativa ? this.ambulanciaService.desativar(id) : this.ambulanciaService.ativar(id);
    obs.subscribe({
      next: () => this.recarregarAmbulancias(),
      error: (e) => { this.error = 'Erro ao alterar status: ' + (e.error?.message || e.message); }
    });
  }

  private recarregarAmbulancias() {
    this.ambulanciaService.listar().subscribe(d => this.ambulancias = d);
  }
}

<div class="admin-page">
  <div class="page-header">
    <h1 class="page-title">Ambulâncias</h1>
    <button class="btn btn-primary" (click)="openModal()">+ Nova Ambulância</button>
  </div>

  <div *ngIf="pageError" class="alert alert-error">{{ pageError }}</div>
  <div *ngIf="loading" class="loading-box">Carregando ambulâncias...</div>

  <div *ngIf="!loading" class="table-card">
    <div class="table-wrapper">
      <table class="data-table">
        <thead><tr>
          <th>ID</th><th>Placa</th><th>Tipo</th><th>Base</th>
          <th>Status Atual</th><th>Ativa</th><th>Ações</th>
        </tr></thead>
        <tbody>
          <tr *ngIf="ambulancias.length === 0"><td colspan="7" style="text-align:center;padding:40px;color:#6b7280">Nenhuma ambulância encontrada</td></tr>
          <tr *ngFor="let amb of ambulancias">
            <td class="text-muted">{{ amb.id }}</td>
            <td style="font-weight:600">{{ amb.placa }}</td>
            <td><span class="badge" [class.badge-warning]="amb.tipo==='UTI'" [class.badge-info]="amb.tipo==='BASICA'">{{ amb.tipo }}</span></td>
            <td>{{ amb.nomeBairroBase || '-' }}</td>
            <td>
              <span class="badge"
                [class.badge-ativo]="amb.status === 'DISPONIVEL'"
                [class.badge-warning]="amb.status === 'EM_ATENDIMENTO'"
                [class.badge-inativo]="amb.status === 'EM_MANUTENCAO' || amb.status === 'INATIVA'">
                {{ amb.status }}
              </span>
            </td>
            <td><span class="badge" [class.badge-ativo]="amb.ativa" [class.badge-inativo]="!amb.ativa">{{ amb.ativa ? 'Sim' : 'Não' }}</span></td>
            <td>
              <div class="actions-cell">
                <button class="btn btn-sm" [class.btn-danger]="amb.ativa" [class.btn-success]="!amb.ativa"
                  (click)="toggleStatus(amb.id, amb.ativa)">
                  {{ amb.ativa ? 'Desativar' : 'Ativar' }}
                </button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div *ngIf="showModal" class="modal-overlay" (click)="closeModal()">
  <div class="modal-box" (click)="$event.stopPropagation()">
    <div class="modal-header">
      <h2>Nova Ambulância</h2>
      <button class="btn-close-icon" (click)="closeModal()">×</button>
    </div>
    <form (ngSubmit)="handleSubmit()">
      <div class="form-group">
        <label class="form-label">Placa *</label>
        <input class="form-input" type="text" [(ngModel)]="formData.placa" name="placa" placeholder="ABC1234" required />
      </div>
      <div class="form-group">
        <label class="form-label">Tipo *</label>
        <select class="form-select" [(ngModel)]="formData.tipo" name="tipo" (ngModelChange)="onTipoChange($event)" required>
          <option value="BASICA">Básica</option>
          <option value="UTI">UTI</option>
        </select>
      </div>
      <div class="form-group">
        <label class="form-label">Bairro Base *</label>
        <!-- Sugestões Dijkstra -->
        <div *ngIf="bairrosSugeridos.length > 0 || loadingSugestoes" class="info-box" style="margin-bottom:12px">
          <strong>💡 Sugestões (Algoritmo Dijkstra):</strong>
          <div *ngIf="loadingSugestoes" style="color:#666;font-size:0.85rem;margin-top:6px">Carregando sugestões...</div>
          <div *ngIf="!loadingSugestoes" class="sugestoes-bairro" style="margin-top:8px">
            <button *ngFor="let s of bairrosSugeridos; let i = index"
              type="button" class="sugestao-btn"
              [class.selecionado]="formData.idBairroBase === s.id.toString()"
              (click)="selecionarSugestao(s.id)">
              <div>
                <div class="sugestao-nome">{{ i+1 }}. {{ s.nome }}</div>
                <div class="sugestao-justif">{{ s.justificativa }}</div>
                <div class="sugestao-meta">
                  <span *ngIf="s.bairrosAlcancaveis > 0">🔗 {{ s.bairrosAlcancaveis }} bairro(s)</span>
                  <span *ngIf="s.ocorrenciasNoBairro > 0">📊 {{ s.ocorrenciasNoBairro }} ocorrência(s)</span>
                  <span *ngIf="s.tempoMedioResposta > 0">⏱️ {{ s.tempoMedioResposta.toFixed(1) }} min</span>
                </div>
              </div>
              <span *ngIf="formData.idBairroBase === s.id.toString()">✓</span>
            </button>
          </div>
        </div>
        <app-autocomplete-select
          [options]="bairros"
          [placeholder]="'Digite ou selecione o bairro base...'"
          [getOptionLabel]="getOptionLabelBairro"
          [getOptionValue]="getOptionValueBairro"
          [required]="true"
          (valueChange)="formData.idBairroBase = $event">
        </app-autocomplete-select>
        <small class="form-helper">Bairro onde a ambulância está estacionada (ponto de partida)</small>
      </div>
      <div *ngIf="modalError" class="form-error">{{ modalError }}</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" (click)="closeModal()">Cancelar</button>
        <button type="submit" class="btn btn-primary">Criar</button>
      </div>
    </form>
  </div>
</div>

// LifeTrack/frontend/src/pages/admin/sections/GerenciarAmbulancias.jsx
import { useState, useEffect } from 'react';
import { ambulanciaService } from '../../../services/ambulanciaService';
import { bairroService } from '../../../services/bairroService';
import { analiseEstrategicaService } from '../../../services/analiseEstrategicaService';
import AutocompleteSelect from '../../../components/AutocompleteSelect';
import '../AdminDashboard.css';

function GerenciarAmbulancias() {
  const [ambulancias, setAmbulancias] = useState([]);
  const [bairros, setBairros] = useState([]);
  const [bairrosSugeridos, setBairrosSugeridos] = useState([]);
  const [loadingSugestoes, setLoadingSugestoes] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [formData, setFormData] = useState({
    placa: '',
    tipo: 'BASICA',
    idBairroBase: '',
  });

  useEffect(() => {
    carregarAmbulancias();
    carregarBairros();
  }, []);

  const carregarBairros = async () => {
    try {
      const dados = await bairroService.listar();
      setBairros(dados);
    } catch (err) {
      console.error('Erro ao carregar bairros:', err);
    }
  };

  const carregarAmbulancias = async () => {
    try {
      setLoading(true);
      const data = await ambulanciaService.listar();
      setAmbulancias(data);
      setError('');
    } catch (err) {
      setError('Erro ao carregar ambulâncias: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      setError('');
      
      // Validar se bairro foi selecionado
      if (!formData.idBairroBase || formData.idBairroBase === '') {
        setError('Selecione um bairro base');
        return;
      }

      const dadosEnvio = {
        placa: formData.placa.trim(),
        tipo: formData.tipo,
        idBairroBase: parseInt(formData.idBairroBase)
      };

      await ambulanciaService.cadastrar(dadosEnvio);
      handleCloseModal();
      carregarAmbulancias();
    } catch (err) {
      setError('Erro ao salvar ambulância: ' + err.message);
    }
  };

  const handleOpenModal = async () => {
    setShowModal(true);
    setBairrosSugeridos([]);
    setLoadingSugestoes(true);
    try {
      const sugestoes = await analiseEstrategicaService.obterBairrosSugeridos();
      setBairrosSugeridos(sugestoes.slice(0, 5)); // Top 5 sugestões
    } catch (err) {
      console.error('Erro ao carregar sugestões:', err);
      // Não mostrar erro, apenas não exibir sugestões
    } finally {
      setLoadingSugestoes(false);
    }
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setFormData({ placa: '', tipo: 'BASICA', idBairroBase: '' });
    setBairrosSugeridos([]);
  };

  const handleSelecionarSugestao = (bairroId) => {
    setFormData({ ...formData, idBairroBase: bairroId.toString() });
  };

  const handleToggleStatus = async (id, ativa) => {
    try {
      if (ativa) {
        await ambulanciaService.desativar(id);
      } else {
        await ambulanciaService.ativar(id);
      }
      carregarAmbulancias();
    } catch (err) {
      setError('Erro ao alterar status: ' + err.message);
    }
  };

  return (
    <div className="admin-dashboard">
      <div className="dashboard-header">
        <h1>Gerenciamento de Ambulâncias</h1>
        <button className="btn-primary" onClick={handleOpenModal}>
          + Nova Ambulância
        </button>
      </div>

      {error && <div className="error-banner">{error}</div>}

      {loading ? (
        <div className="loading">Carregando ambulâncias...</div>
      ) : (
        <div className="usuarios-table-container">
          <table className="usuarios-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Placa</th>
                <th>Tipo</th>
                <th>Status</th>
                <th>Bairro Base</th>
                <th>Ativa</th>
                <th>Ações</th>
              </tr>
            </thead>
            <tbody>
              {ambulancias.length === 0 ? (
                <tr>
                  <td colSpan="7" className="empty-message">
                    Nenhuma ambulância cadastrada
                  </td>
                </tr>
              ) : (
                ambulancias.map((amb) => (
                  <tr key={amb.id}>
                    <td>{amb.id}</td>
                    <td>{amb.placa}</td>
                    <td>{amb.tipo}</td>
                    <td>
                      <span className="status-badge ativo">{amb.status}</span>
                    </td>
                    <td>{amb.bairroBase?.nome || 'N/A'}</td>
                    <td>
                      <span className={`status-badge ${amb.ativa ? 'ativo' : 'inativo'}`}>
                        {amb.ativa ? 'Sim' : 'Não'}
                      </span>
                    </td>
                    <td className="actions">
                      <button
                        className={`btn-toggle ${amb.ativa ? 'desativar' : 'ativar'}`}
                        onClick={() => handleToggleStatus(amb.id, amb.ativa)}
                      >
                        {amb.ativa ? 'Desativar' : 'Ativar'}
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      )}

      {showModal && (
        <div className="modal-overlay" onClick={handleCloseModal}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>Nova Ambulância</h2>
              <button className="btn-close" onClick={handleCloseModal}>×</button>
            </div>
            <form onSubmit={handleSubmit}>
              <div className="form-group">
                <label>Placa *</label>
                <input
                  type="text"
                  value={formData.placa}
                  onChange={(e) => setFormData({ ...formData, placa: e.target.value })}
                  required
                  placeholder="ABC-1234"
                />
              </div>
              <div className="form-group">
                <label>Tipo *</label>
                <select
                  value={formData.tipo}
                  onChange={(e) => setFormData({ ...formData, tipo: e.target.value })}
                  required
                >
                  <option value="BASICA">Básica</option>
                  <option value="UTI">UTI</option>
                </select>
              </div>
              <div className="form-group">
                <label>Bairro Base *</label>
                {bairrosSugeridos.length > 0 && (
                  <div style={{ 
                    marginBottom: '12px', 
                    padding: '12px', 
                    backgroundColor: '#f0f7ff', 
                    borderRadius: '6px',
                    border: '1px solid #4a90e2'
                  }}>
                    <div style={{ 
                      fontSize: '0.9rem', 
                      fontWeight: '600', 
                      color: '#2c5aa0',
                      marginBottom: '8px',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '6px'
                    }}>
                      <span>💡</span>
                      <span>Sugestões baseadas no algoritmo Dijkstra e análise de ocorrências:</span>
                    </div>
                    <div style={{ 
                      fontSize: '0.8rem', 
                      color: '#4b5563',
                      marginBottom: '8px',
                      paddingLeft: '24px',
                      fontStyle: 'italic'
                    }}>
                      O algoritmo Dijkstra calcula o menor caminho na rede viária, analisando tempo médio de resposta 
                      para outros bairros com ocorrências, garantindo posicionamento estratégico otimizado.
                    </div>
                    {loadingSugestoes ? (
                      <div style={{ color: '#666', fontSize: '0.85rem' }}>Carregando sugestões...</div>
                    ) : (
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                        {bairrosSugeridos.map((sugestao, idx) => (
                          <button
                            key={sugestao.id}
                            type="button"
                            onClick={() => handleSelecionarSugestao(sugestao.id)}
                            style={{
                              textAlign: 'left',
                              padding: '8px 12px',
                              backgroundColor: formData.idBairroBase === sugestao.id.toString() ? '#4a90e2' : '#fff',
                              color: formData.idBairroBase === sugestao.id.toString() ? '#fff' : '#333',
                              border: `1px solid ${formData.idBairroBase === sugestao.id.toString() ? '#4a90e2' : '#ddd'}`,
                              borderRadius: '4px',
                              cursor: 'pointer',
                              fontSize: '0.85rem',
                              transition: 'all 0.2s',
                              display: 'flex',
                              justifyContent: 'space-between',
                              alignItems: 'center'
                            }}
                            onMouseEnter={(e) => {
                              if (formData.idBairroBase !== sugestao.id.toString()) {
                                e.target.style.backgroundColor = '#e8f4fd';
                              }
                            }}
                            onMouseLeave={(e) => {
                              if (formData.idBairroBase !== sugestao.id.toString()) {
                                e.target.style.backgroundColor = '#fff';
                              }
                            }}
                          >
                            <div style={{ flex: 1 }}>
                              <div style={{ fontWeight: '600' }}>
                                {idx + 1}. {sugestao.nome}
                              </div>
                              <div style={{ 
                                fontSize: '0.75rem', 
                                opacity: 0.8,
                                marginTop: '2px'
                              }}>
                                {sugestao.justificativa}
                              </div>
                              <div style={{ 
                                fontSize: '0.7rem', 
                                marginTop: '4px',
                                display: 'flex',
                                gap: '12px',
                                opacity: 0.7,
                                flexWrap: 'wrap'
                              }}>
                                {sugestao.bairrosAlcancaveis !== undefined && sugestao.bairrosAlcancaveis > 0 && (
                                  <span style={{ 
                                    fontWeight: '600', 
                                    color: sugestao.bairrosAlcancaveis >= 10 ? '#059669' : '#6b7280'
                                  }}>
                                    🔗 {sugestao.bairrosAlcancaveis} bairro(s) alcançável(is) via Dijkstra
                                  </span>
                                )}
                                {sugestao.ocorrenciasNoBairro > 0 && (
                                  <span>📊 {sugestao.ocorrenciasNoBairro} ocorrência(s)</span>
                                )}
                                {sugestao.tempoMedioResposta > 0 && (
                                  <span>⏱️ {sugestao.tempoMedioResposta.toFixed(1)} min médio</span>
                                )}
                                {sugestao.ambulanciasExistentes > 0 && (
                                  <span>🚑 {sugestao.ambulanciasExistentes} ambulância(s)</span>
                                )}
                              </div>
                            </div>
                            {formData.idBairroBase === sugestao.id.toString() && (
                              <span style={{ marginLeft: '8px', fontSize: '1.2rem' }}>✓</span>
                            )}
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                )}
                <AutocompleteSelect
                  options={bairros}
                  value={formData.idBairroBase}
                  onChange={(value) => setFormData({ ...formData, idBairroBase: value })}
                  placeholder="Digite ou selecione o bairro base..."
                  getOptionLabel={(opt) => opt.nome}
                  getOptionValue={(opt) => opt.id.toString()}
                  required={true}
                />
                <small style={{ color: '#666', fontSize: '0.85rem', marginTop: '4px', display: 'block' }}>
                  Bairro onde a ambulância está estacionada (ponto de partida)
                </small>
              </div>
              {error && <div className="form-error">{error}</div>}
              <div className="modal-actions">
                <button type="button" className="btn-secondary" onClick={handleCloseModal}>
                  Cancelar
                </button>
                <button type="submit" className="btn-primary">Criar</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

export default GerenciarAmbulancias;
