// LifeTrack/frontend/src/pages/admin/sections/GerenciarFuncionarios.jsx
import { useState, useEffect } from 'react';
import { profissionalService } from '../../../services/profissionalService';
import '../AdminDashboard.css';

function GerenciarFuncionarios() {
  const [profissionais, setProfissionais] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [filtroTurno, setFiltroTurno] = useState('');
  const [filtroStatus, setFiltroStatus] = useState('');
  const [formData, setFormData] = useState({
    nome: '',
    funcao: 'MEDICO',
    contato: '',
    turno: 'MANHA',
    status: 'DISPONIVEL',
    ativo: true,
  });

  useEffect(() => {
    carregarProfissionais();
  }, [filtroTurno, filtroStatus]);

  const carregarProfissionais = async () => {
    try {
      setLoading(true);
      const data = await profissionalService.listar(
        filtroTurno || null,
        filtroStatus || null
      );
      setProfissionais(data);
      setError('');
    } catch (err) {
      setError('Erro ao carregar profissionais: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      setError('');
      if (editingId) {
        await profissionalService.editar(editingId, formData);
      } else {
        await profissionalService.cadastrar(formData);
      }
      handleCloseModal();
      carregarProfissionais();
    } catch (err) {
      setError('Erro ao salvar profissional: ' + err.message);
    }
  };

  const handleEdit = async (id) => {
    try {
      const prof = await profissionalService.buscarPorId(id);
      setFormData({
        nome: prof.nome,
        funcao: prof.funcao,
        contato: prof.contato || '',
        turno: prof.turno || 'MANHA',
        status: prof.status || 'DISPONIVEL',
        ativo: prof.ativo !== undefined ? prof.ativo : true,
      });
      setEditingId(id);
      setShowModal(true);
    } catch (err) {
      setError('Erro ao carregar profissional: ' + err.message);
    }
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setEditingId(null);
    setFormData({
      nome: '',
      funcao: 'MEDICO',
      contato: '',
      turno: 'MANHA',
      status: 'DISPONIVEL',
      ativo: true,
    });
  };

  const handleAlterarStatus = async (id, novoStatus) => {
    try {
      await profissionalService.alterarStatus(id, novoStatus);
      carregarProfissionais();
    } catch (err) {
      setError('Erro ao alterar status: ' + err.message);
    }
  };

  const handleDesativar = async (id) => {
    if (!window.confirm('Tem certeza que deseja desativar este profissional?')) {
      return;
    }
    try {
      await profissionalService.desativar(id);
      carregarProfissionais();
    } catch (err) {
      setError('Erro ao desativar profissional: ' + err.message);
    }
  };

  const getStatusBadgeClass = (status) => {
    switch (status) {
      case 'DISPONIVEL':
        return 'status-badge ativo';
      case 'EM_ATENDIMENTO':
        return 'status-badge em-atendimento';
      case 'EM_FOLGA':
        return 'status-badge em-folga';
      case 'INATIVO':
        return 'status-badge inativo';
      default:
        return 'status-badge';
    }
  };

  const getStatusLabel = (status) => {
    switch (status) {
      case 'DISPONIVEL':
        return 'Disponível';
      case 'EM_ATENDIMENTO':
        return 'Em Atendimento';
      case 'EM_FOLGA':
        return 'Em Folga';
      case 'INATIVO':
        return 'Inativo';
      default:
        return status;
    }
  };

  const getTurnoLabel = (turno) => {
    switch (turno) {
      case 'MANHA':
        return 'Manhã';
      case 'TARDE':
        return 'Tarde';
      case 'NOITE':
        return 'Noite';
      default:
        return turno;
    }
  };

  return (
    <div className="admin-dashboard">
      <div className="dashboard-header">
        <h1>Gerenciamento de Funcionários</h1>
        <button className="btn-primary" onClick={() => setShowModal(true)}>
          + Novo Funcionário
        </button>
      </div>

      {error && <div className="error-banner">{error}</div>}

      {/* Filtros */}
      <div style={{ marginBottom: '20px', display: 'flex', gap: '12px', alignItems: 'center' }}>
        <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
          <label style={{ fontWeight: '600' }}>Filtros:</label>
          <select
            value={filtroTurno}
            onChange={(e) => setFiltroTurno(e.target.value)}
            style={{ padding: '6px 12px', borderRadius: '4px', border: '1px solid #ddd' }}
          >
            <option value="">Todos os Turnos</option>
            <option value="MANHA">Manhã</option>
            <option value="TARDE">Tarde</option>
            <option value="NOITE">Noite</option>
          </select>
          <select
            value={filtroStatus}
            onChange={(e) => setFiltroStatus(e.target.value)}
            style={{ padding: '6px 12px', borderRadius: '4px', border: '1px solid #ddd' }}
          >
            <option value="">Todos os Status</option>
            <option value="DISPONIVEL">Disponível</option>
            <option value="EM_ATENDIMENTO">Em Atendimento</option>
            <option value="EM_FOLGA">Em Folga</option>
            <option value="INATIVO">Inativo</option>
          </select>
        </div>
      </div>

      {loading ? (
        <div className="loading">Carregando profissionais...</div>
      ) : (
        <div className="usuarios-table-container">
          <table className="usuarios-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Função</th>
                <th>Turno</th>
                <th>Status</th>
                <th>Contato</th>
                <th>Ativo</th>
                <th>Ações</th>
              </tr>
            </thead>
            <tbody>
              {profissionais.length === 0 ? (
                <tr>
                  <td colSpan="8" className="empty-message">
                    Nenhum profissional encontrado
                  </td>
                </tr>
              ) : (
                profissionais.map((prof) => (
                  <tr key={prof.id}>
                    <td>{prof.id}</td>
                    <td>{prof.nome}</td>
                    <td>
                      <span className="role-badge">{prof.funcao}</span>
                    </td>
                    <td>{getTurnoLabel(prof.turno)}</td>
                    <td>
                      <span className={getStatusBadgeClass(prof.status)}>
                        {getStatusLabel(prof.status)}
                      </span>
                    </td>
                    <td>{prof.contato || '-'}</td>
                    <td>
                      <span className={`status-badge ${prof.ativo ? 'ativo' : 'inativo'}`}>
                        {prof.ativo ? 'Sim' : 'Não'}
                      </span>
                    </td>
                    <td className="actions" style={{ display: 'flex', gap: '4px', flexWrap: 'wrap' }}>
                      <button
                        className="btn-toggle editar"
                        onClick={() => handleEdit(prof.id)}
                        style={{ backgroundColor: '#4a90e2', color: 'white' }}
                      >
                        Editar
                      </button>
                      {prof.status === 'DISPONIVEL' && (
                        <button
                          className="btn-toggle"
                          onClick={() => handleAlterarStatus(prof.id, 'EM_FOLGA')}
                          style={{ backgroundColor: '#f39c12', color: 'white', fontSize: '0.85rem' }}
                        >
                          Folga
                        </button>
                      )}
                      {prof.status === 'EM_FOLGA' && (
                        <button
                          className="btn-toggle"
                          onClick={() => handleAlterarStatus(prof.id, 'DISPONIVEL')}
                          style={{ backgroundColor: '#27ae60', color: 'white', fontSize: '0.85rem' }}
                        >
                          Disponível
                        </button>
                      )}
                      {prof.ativo && (
                        <button
                          className="btn-toggle desativar"
                          onClick={() => handleDesativar(prof.id)}
                        >
                          Desativar
                        </button>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      )}

      {showModal && (
        <div className="modal-overlay" onClick={handleCloseModal}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>{editingId ? 'Editar Funcionário' : 'Novo Funcionário'}</h2>
              <button className="btn-close" onClick={handleCloseModal}>×</button>
            </div>
            <form onSubmit={handleSubmit}>
              <div className="form-group">
                <label>Nome Completo *</label>
                <input
                  type="text"
                  value={formData.nome}
                  onChange={(e) => setFormData({ ...formData, nome: e.target.value })}
                  required
                  placeholder="Dr. João Silva"
                />
              </div>
              <div className="form-group">
                <label>Função *</label>
                <select
                  value={formData.funcao}
                  onChange={(e) => setFormData({ ...formData, funcao: e.target.value })}
                  required
                >
                  <option value="MEDICO">Médico</option>
                  <option value="ENFERMEIRO">Enfermeiro</option>
                  <option value="CONDUTOR">Condutor</option>
                </select>
              </div>
              <div className="form-group">
                <label>Turno *</label>
                <select
                  value={formData.turno}
                  onChange={(e) => setFormData({ ...formData, turno: e.target.value })}
                  required
                >
                  <option value="MANHA">Manhã</option>
                  <option value="TARDE">Tarde</option>
                  <option value="NOITE">Noite</option>
                </select>
              </div>
              <div className="form-group">
                <label>Status *</label>
                <select
                  value={formData.status}
                  onChange={(e) => setFormData({ ...formData, status: e.target.value })}
                  required
                >
                  <option value="DISPONIVEL">Disponível</option>
                  <option value="EM_ATENDIMENTO">Em Atendimento</option>
                  <option value="EM_FOLGA">Em Folga</option>
                  <option value="INATIVO">Inativo</option>
                </select>
              </div>
              <div className="form-group">
                <label>Contato</label>
                <input
                  type="text"
                  value={formData.contato}
                  onChange={(e) => setFormData({ ...formData, contato: e.target.value })}
                  placeholder="(11) 99999-1111"
                />
              </div>
              {editingId && (
                <div className="form-group">
                  <label>
                    <input
                      type="checkbox"
                      checked={formData.ativo}
                      onChange={(e) => setFormData({ ...formData, ativo: e.target.checked })}
                    />
                    {' '}Ativo
                  </label>
                </div>
              )}
              {error && <div className="form-error">{error}</div>}
              <div className="modal-actions">
                <button type="button" className="btn-secondary" onClick={handleCloseModal}>
                  Cancelar
                </button>
                <button type="submit" className="btn-primary">
                  {editingId ? 'Salvar' : 'Criar'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

export default GerenciarFuncionarios;

// LifeTrack/frontend/src/app/pages/admin/gerenciar-funcionarios/gerenciar-funcionarios.component.ts
import { Component, OnInit, OnChanges, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ProfissionalService } from '../../../core/services/profissional.service';

@Component({
  selector: 'app-gerenciar-funcionarios',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './gerenciar-funcionarios.component.html',
  styleUrls: ['../admin.shared.css']
})
export class GerenciarFuncionariosComponent implements OnInit {
  profissionais: any[] = [];
  loading = true;
  error = '';
  showModal = false;
  editingId: number | null = null;
  filtroTurno = '';
  filtroStatus = '';
  formData = { nome: '', funcao: 'MEDICO', contato: '', turno: 'MANHA', status: 'DISPONIVEL', ativo: true };

  private profissionalService = inject(ProfissionalService);

  ngOnInit() { this.carregarProfissionais(); }

  carregarProfissionais() {
    this.loading = true;
    this.profissionalService.listar(this.filtroTurno || null, this.filtroStatus || null).subscribe({
      next: (d) => { this.profissionais = d; this.error = ''; this.loading = false; },
      error: (e) => { this.error = 'Erro ao carregar: ' + (e.message || e); this.loading = false; }
    });
  }

  handleEdit(id: number) {
    this.profissionalService.buscarPorId(id).subscribe({
      next: (prof: any) => {
        if (prof.status === 'EM_ATENDIMENTO') { this.error = 'Não é possível editar funcionário em atendimento.'; return; }
        this.formData = { nome: prof.nome, funcao: prof.funcao, contato: prof.contato || '', turno: prof.turno || 'MANHA', status: prof.status || 'DISPONIVEL', ativo: prof.ativo ?? true };
        this.editingId = id;
        this.error = '';
        this.showModal = true;
      },
      error: (e) => { this.error = 'Erro ao carregar: ' + (e.message || e); }
    });
  }

  openNew() {
    this.editingId = null;
    this.formData = { nome: '', funcao: 'MEDICO', contato: '', turno: 'MANHA', status: 'DISPONIVEL', ativo: true };
    this.error = '';
    this.showModal = true;
  }

  closeModal() { this.showModal = false; this.editingId = null; }

  handleSubmit() {
    this.error = '';
    const obs = this.editingId
      ? this.profissionalService.editar(this.editingId, this.formData as any)
      : this.profissionalService.cadastrar(this.formData as any);
    obs.subscribe({
      next: () => { this.closeModal(); this.carregarProfissionais(); },
      error: (e) => { this.error = 'Erro ao salvar: ' + (e.error?.message || e.message); }
    });
  }

  alterarStatus(id: number, novoStatus: string) {
    this.profissionalService.alterarStatus(id, novoStatus).subscribe({
      next: () => this.carregarProfissionais(),
      error: (e) => { this.error = 'Erro ao alterar status: ' + (e.error?.message || e.message); }
    });
  }

  desativar(id: number) {
    if (!window.confirm('Tem certeza que deseja desativar este profissional?')) return;
    this.profissionalService.desativar(id).subscribe({
      next: () => this.carregarProfissionais(),
      error: (e) => { this.error = 'Erro ao desativar: ' + (e.error?.message || e.message); }
    });
  }

  getStatusBadgeClass(status: string): string {
    const map: Record<string, string> = { DISPONIVEL: 'badge badge-ativo', EM_ATENDIMENTO: 'badge badge-warning', EM_FOLGA: 'badge badge-info', INATIVO: 'badge badge-inativo' };
    return map[status] || 'badge';
  }

  getStatusLabel(status: string): string {
    const map: Record<string, string> = { DISPONIVEL: 'Disponível', EM_ATENDIMENTO: 'Em Atendimento', EM_FOLGA: 'Em Folga', INATIVO: 'Inativo' };
    return map[status] || status;
  }

  getTurnoLabel(turno: string): string {
    const map: Record<string, string> = { MANHA: 'Manhã', TARDE: 'Tarde', NOITE: 'Noite' };
    return map[turno] || turno;
  }
}

<div class="admin-page">
  <div class="page-header">
    <h1 class="page-title">Gerenciamento de Funcionários</h1>
    <button class="btn btn-primary" (click)="openNew()">+ Novo Funcionário</button>
  </div>

  <div *ngIf="error" class="alert alert-error">{{ error }}</div>

  <div class="filters-bar">
    <label>Filtros:</label>
    <select class="form-select-sm" [(ngModel)]="filtroTurno" (change)="carregarProfissionais()">
      <option value="">Todos os Turnos</option>
      <option value="MANHA">Manhã</option>
      <option value="TARDE">Tarde</option>
      <option value="NOITE">Noite</option>
    </select>
    <select class="form-select-sm" [(ngModel)]="filtroStatus" (change)="carregarProfissionais()">
      <option value="">Todos os Status</option>
      <option value="DISPONIVEL">Disponível</option>
      <option value="EM_ATENDIMENTO">Em Atendimento</option>
      <option value="EM_FOLGA">Em Folga</option>
      <option value="INATIVO">Inativo</option>
    </select>
  </div>

  <div *ngIf="loading" class="loading-box">Carregando profissionais...</div>

  <div *ngIf="!loading" class="table-card">
    <div class="table-wrapper">
      <table class="data-table">
        <thead><tr>
          <th>ID</th><th>Nome</th><th>Função</th><th>Turno</th>
          <th>Status</th><th>Contato</th><th>Ativo</th><th>Ações</th>
        </tr></thead>
        <tbody>
          <tr *ngIf="profissionais.length === 0"><td colspan="8" style="text-align:center;padding:40px;color:#6b7280">Nenhum profissional encontrado</td></tr>
          <tr *ngFor="let prof of profissionais">
            <td class="text-muted">{{ prof.id }}</td>
            <td>{{ prof.nome }}</td>
            <td><span class="badge badge-info">{{ prof.funcao }}</span></td>
            <td>{{ getTurnoLabel(prof.turno) }}</td>
            <td><span [ngClass]="getStatusBadgeClass(prof.status)">{{ getStatusLabel(prof.status) }}</span></td>
            <td>{{ prof.contato || '-' }}</td>
            <td>
              <span class="badge" [class.badge-ativo]="prof.ativo" [class.badge-inativo]="!prof.ativo">{{ prof.ativo ? 'Sim' : 'Não' }}</span>
            </td>
            <td>
              <div class="actions-cell">
                <button class="btn btn-sm btn-secondary"
                  [disabled]="prof.status === 'EM_ATENDIMENTO'"
                  [title]="prof.status === 'EM_ATENDIMENTO' ? 'Em atendimento' : 'Editar'"
                  (click)="handleEdit(prof.id)">Editar</button>
                <button *ngIf="prof.status === 'DISPONIVEL'" class="btn btn-sm btn-warning" (click)="alterarStatus(prof.id, 'EM_FOLGA')">Folga</button>
                <button *ngIf="prof.status === 'EM_FOLGA'" class="btn btn-sm btn-success" (click)="alterarStatus(prof.id, 'DISPONIVEL')">Disponível</button>
                <button *ngIf="prof.ativo" class="btn btn-sm btn-danger" (click)="desativar(prof.id)">Desativar</button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div *ngIf="showModal" class="modal-overlay" (click)="closeModal()">
  <div class="modal-box" (click)="$event.stopPropagation()">
    <div class="modal-header">
      <h2>{{ editingId ? 'Editar Funcionário' : 'Novo Funcionário' }}</h2>
      <button class="btn-close-icon" (click)="closeModal()">×</button>
    </div>
    <form (ngSubmit)="handleSubmit()">
      <div class="form-group">
        <label class="form-label">Nome Completo *</label>
        <input class="form-input" type="text" [(ngModel)]="formData.nome" name="nome" placeholder="Dr. João Silva" required />
      </div>
      <div class="form-group">
        <label class="form-label">Função *</label>
        <select class="form-select" [(ngModel)]="formData.funcao" name="funcao" required>
          <option value="MEDICO">Médico</option>
          <option value="ENFERMEIRO">Enfermeiro</option>
          <option value="CONDUTOR">Condutor</option>
        </select>
      </div>
      <div class="form-group">
        <label class="form-label">Turno *</label>
        <select class="form-select" [(ngModel)]="formData.turno" name="turno" required>
          <option value="MANHA">Manhã</option>
          <option value="TARDE">Tarde</option>
          <option value="NOITE">Noite</option>
        </select>
      </div>
      <div class="form-group">
        <label class="form-label">Status *</label>
        <select class="form-select" [(ngModel)]="formData.status" name="status" required>
          <option value="DISPONIVEL">Disponível</option>
          <option value="EM_ATENDIMENTO">Em Atendimento</option>
          <option value="EM_FOLGA">Em Folga</option>
          <option value="INATIVO">Inativo</option>
        </select>
      </div>
      <div class="form-group">
        <label class="form-label">Contato *</label>
        <input class="form-input" type="tel" [(ngModel)]="formData.contato" name="contato" placeholder="(11) 99999-1111" required />
      </div>
      <div *ngIf="editingId" class="form-group" style="display:flex;align-items:center;gap:8px">
        <input type="checkbox" [(ngModel)]="formData.ativo" name="ativo" id="ativo" />
        <label for="ativo" style="margin:0;font-weight:600;color:#374151">Ativo</label>
      </div>
      <div *ngIf="error" class="form-error">{{ error }}</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" (click)="closeModal()">Cancelar</button>
        <button type="submit" class="btn btn-primary">{{ editingId ? 'Salvar' : 'Criar' }}</button>
      </div>
    </form>
  </div>
</div>
