// LifeTrack/frontend/src/app/shared/components/sla-timer/sla-timer.component.ts
import { Component, Input, OnInit, OnDestroy, OnChanges, SimpleChanges, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { OcorrenciaService } from '../../../core/services/ocorrencia.service';

@Component({
  selector: 'app-sla-timer',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './sla-timer.component.html',
  styleUrls: ['./sla-timer.component.css']
})
export class SlaTimerComponent implements OnInit, OnDestroy, OnChanges {
  @Input() ocorrenciaId!: number;
  @Input() status!: string;

  timer: any = null;
  loading: boolean = true;
  error: string | null = null;
  percentual: number = 0;
  etapas: any = { ateDespacho: 0, ateChegada: 0, retorno: 0, total: 0 };

  private ocorrenciaService = inject(OcorrenciaService);

  // Status que devem mostrar o timer
  private readonly statusComTimer = ['ABERTA', 'DESPACHADA', 'EM_ATENDIMENTO', 'CONCLUIDA'];

  ngOnInit() {
    this.iniciarTimer();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['ocorrenciaId'] || changes['status']) {
      this.iniciarTimer();
    }
  }

  ngOnDestroy() {
  }

  private iniciarTimer() {
    if (!this.ocorrenciaId || !this.statusComTimer.includes(this.status)) {
      this.loading = false;
      return;
    }

    this.carregarTimer();
  }

  private carregarTimer() {
    this.ocorrenciaService.obterTimer(this.ocorrenciaId).subscribe({
      next: (dados) => {
        this.timer = dados;
        this.error = null;
        this.loading = false;
        this.atualizarCalculos();
      },
      error: (err) => {
        this.error = err.message || 'Erro ao carregar timer';
        this.loading = false;
      }
    });
  }

  private atualizarCalculos() {
    if (!this.timer) return;
    this.percentual = this.calcularPercentualSla();
    this.etapas = this.calcularEtapasProgresso();
  }

  getSlaStatusClass(): string {
    if (this.timer?.slaExcedido) return 'sla-excedido';
    if (this.timer?.slaEmRisco) return 'sla-risco';
    return 'sla-ok';
  }

  getSlaStatusText(): string {
    if (this.timer?.slaExcedido) return 'SLA Excedido';
    if (this.timer?.slaEmRisco) return 'SLA em Risco';
    return 'SLA OK';
  }

  private calcularPercentualSla(): number {
    if (!this.timer?.slaMinutos || this.timer.slaMinutos === 0) return 0;
    const percentual = ((this.timer.tempoSlaDecorridoMinutos || 0) / this.timer.slaMinutos) * 100;
    return Math.min(100, Math.max(0, percentual));
  }

  private calcularEtapasProgresso(): any {
    if (!this.timer?.slaMinutos || this.timer.slaMinutos === 0) {
      return { ateDespacho: 0, ateChegada: 0, retorno: 0, total: 0 };
    }

    const slaTotalMinutos = this.timer.slaMinutos;
    let ateDespachoPercentual = 0;
    let ateChegadaPercentual = 0;
    let retornoPercentual = 0;

    // Calcular tempo até despacho (desde abertura até despacho)
    if (this.timer.foiDespachada && this.timer.dataHoraDespacho && this.timer.dataHoraAbertura) {
      try {
        const tempoAteDespachoSegundos = (new Date(this.timer.dataHoraDespacho).getTime() - new Date(this.timer.dataHoraAbertura).getTime()) / 1000;
        const tempoAteDespachoMinutos = tempoAteDespachoSegundos / 60;
        ateDespachoPercentual = (tempoAteDespachoMinutos / slaTotalMinutos) * 100;
      } catch (e) {
        ateDespachoPercentual = 0;
      }
    }

    // Calcular tempo de ida (despacho até chegada)
    if (this.timer.tempoAteChegadaMinutos !== null && this.timer.tempoAteChegadaMinutos !== undefined) {
      ateChegadaPercentual = (this.timer.tempoAteChegadaMinutos / slaTotalMinutos) * 100;
    }

    // Calcular tempo de retorno (apenas se OS está finalizada)
    if (this.timer.foiConcluida && this.timer.tempoRetornoDecorridoMinutos !== null && this.timer.tempoRetornoDecorridoMinutos !== undefined) {
      retornoPercentual = (this.timer.tempoRetornoDecorridoMinutos / slaTotalMinutos) * 100;
    }

    // Calcular o total usado do SLA (apenas tempo até chegada, sem retorno)
    const tempoSlaUsado = (this.timer.tempoSlaDecorridoMinutos || 0);
    const totalPercentual = (tempoSlaUsado / slaTotalMinutos) * 100;

    // Normalizar para que a soma das etapas visíveis não exceda o total
    const tempoAteChegadaTotal = ateDespachoPercentual + ateChegadaPercentual;

    // Se o tempo usado é diferente do esperado, ajustar proporcionalmente
    if (tempoAteChegadaTotal > 0 && totalPercentual > 0) {
      const fatorAjuste = Math.min(1, totalPercentual / tempoAteChegadaTotal);
      ateDespachoPercentual *= fatorAjuste;
      ateChegadaPercentual *= fatorAjuste;
    }

    return {
      ateDespacho: Math.min(100, Math.max(0, ateDespachoPercentual)),
      ateChegada: Math.min(100, Math.max(0, ateChegadaPercentual)),
      retorno: Math.min(100, Math.max(0, retornoPercentual)),
      total: Math.min(100, Math.max(0, totalPercentual))
    };
  }

  get showTimer(): boolean {
    return !!this.ocorrenciaId && this.statusComTimer.includes(this.status);
  }
}

<div *ngIf="showTimer">
  <div *ngIf="loading" class="sla-timer-container">
    <div class="sla-loading">Carregando timer...</div>
  </div>

  <div *ngIf="!loading && !error && timer" class="sla-timer-container" [ngClass]="getSlaStatusClass()">
    <div class="sla-header">
      <div class="sla-status-badge">
        <span class="sla-status-icon">
          {{ timer.slaExcedido ? '⚠️' : timer.slaEmRisco ? '⏱️' : '✅' }}
        </span>
        <span class="sla-status-text">{{ getSlaStatusText() }}</span>
      </div>
      <div class="sla-tempo-restante">
        {{ timer.tempoRestanteFormatado || '--' }}
      </div>
    </div>
    
    <div class="sla-progress-bar-container">
      <div class="sla-progress-segmented">
        <!-- Etapa 1: Tempo até despacho -->
        <div *ngIf="etapas.ateDespacho > 0"
             class="sla-progress-segment sla-segment-ate-despacho"
             [style.width.%]="etapas.ateDespacho < 1 ? 1 : etapas.ateDespacho"
             title="Tempo desde abertura até despacho">
        </div>
        <!-- Etapa 2: Tempo de deslocamento (despacho até chegada) -->
        <div *ngIf="etapas.ateChegada > 0"
             class="sla-progress-segment sla-segment-ida"
             [style.width.%]="etapas.ateChegada < 1 ? 1 : etapas.ateChegada"
             title="Tempo de deslocamento: base → destino">
        </div>
        <!-- Etapa 3: Tempo de retorno (apenas se OS está finalizada) -->
        <div *ngIf="timer.foiConcluida && etapas.retorno > 0"
             class="sla-progress-segment sla-segment-retorno"
             [style.width.%]="etapas.retorno < 1 ? 1 : etapas.retorno"
             title="Tempo de retorno à base (não conta para SLA)">
        </div>
        <!-- Barra de fundo mostrando progresso total do SLA -->
        <div *ngIf="percentual > 0"
             style="position: absolute; top: 0; left: 0; height: 100%; opacity: 0.15; z-index: 0; border-radius: 10px;"
             [style.width.%]="percentual > 100 ? 100 : percentual"
             [style.backgroundColor]="timer.slaExcedido ? '#dc3545' : timer.slaEmRisco ? '#ffc107' : '#10b981'">
        </div>
      </div>
      <div class="sla-progress-text">
        {{ timer.slaMinutos ? (percentual | number:'1.1-1') + '% do SLA utilizado' : 'Aguardando SLA...' }}
      </div>
      <div class="sla-progress-legend">
        <span *ngIf="etapas.ateDespacho > 0" class="sla-legend-item">
          <span class="sla-legend-color sla-legend-ate-despacho"></span>
          Até Despacho
        </span>
        <span *ngIf="etapas.ateChegada > 0" class="sla-legend-item">
          <span class="sla-legend-color sla-legend-ida"></span>
          Deslocamento
        </span>
        <span *ngIf="timer.foiConcluida && etapas.retorno > 0" class="sla-legend-item">
          <span class="sla-legend-color sla-legend-retorno"></span>
          Retorno (não conta para SLA)
        </span>
      </div>
    </div>

    <div class="sla-detalhes">
      <div class="sla-detalhe-item">
        <span class="sla-detalhe-label">Tempo Total:</span>
        <span class="sla-detalhe-valor">{{ timer.tempoTotalFormatado || '--' }}</span>
      </div>
      <div *ngIf="timer.tempoRestanteAteChegadaMinutos !== null && timer.tempoRestanteAteChegadaMinutos !== undefined && !timer.chegouLocal" class="sla-detalhe-item">
        <span class="sla-detalhe-label">Tempo Restante até Chegada:</span>
        <span class="sla-detalhe-valor" [style.color]="timer.tempoRestanteAteChegadaMinutos <= 0 ? '#dc3545' : '#28a745'" style="font-weight: bold;">
          {{ timer.tempoRestanteAteChegadaMinutos > 0 ? timer.tempoRestanteAteChegadaMinutos + 'm' : 'Chegou!' }}
        </span>
      </div>
      <div *ngIf="timer.tempoAteChegadaMinutos !== null && timer.chegouLocal" class="sla-detalhe-item">
        <span class="sla-detalhe-label">Tempo até Chegada:</span>
        <span class="sla-detalhe-valor">
          {{ timer.tempoAteChegadaMinutos !== null ? timer.tempoAteChegadaMinutos + 'm' : '--' }}
        </span>
      </div>
      <div *ngIf="timer.distanciaKm !== null && timer.distanciaKm !== undefined" class="sla-detalhe-item">
        <span class="sla-detalhe-label">Distância:</span>
        <span class="sla-detalhe-valor">
          {{ timer.distanciaKm | number:'1.2-2' }} km
        </span>
      </div>
      <div *ngIf="timer.slaMinutos" class="sla-detalhe-item">
        <span class="sla-detalhe-label">SLA Total:</span>
        <span class="sla-detalhe-valor">{{ timer.slaMinutos }}m</span>
      </div>
      <ng-container *ngIf="timer.foiConcluida">
        <div *ngIf="timer.retornouBase; else retornoAndamento" class="sla-detalhe-item">
          <span class="sla-detalhe-label">Tempo Retorno:</span>
          <span class="sla-detalhe-valor" style="color: #28a745;">
            {{ timer.tempoRetornoDecorridoMinutos !== null ? timer.tempoRetornoDecorridoMinutos + 'm' : '--' }} ✅
          </span>
        </div>
        <ng-template #retornoAndamento>
          <div class="sla-detalhe-item">
            <span class="sla-detalhe-label">Tempo Restante Retorno:</span>
            <span class="sla-detalhe-valor" style="color: #ffc107; font-weight: bold;">
              {{ timer.tempoRetornoMinutos !== null && timer.tempoRetornoDecorridoMinutos !== null ? (timer.tempoRetornoMinutos - timer.tempoRetornoDecorridoMinutos > 0 ? timer.tempoRetornoMinutos - timer.tempoRetornoDecorridoMinutos : 0) + 'm' : '--' }} (em andamento)
            </span>
          </div>
        </ng-template>
        <div *ngIf="timer.retornouBase" class="sla-detalhe-item">
          <span class="sla-detalhe-label">Status:</span>
          <span class="sla-detalhe-valor" style="color: #28a745; font-weight: bold;">
            Ambulância e equipe disponíveis ✅
          </span>
        </div>
      </ng-container>
    </div>
  </div>
</div>

// LifeTrack/frontend/src/components/SLATimer.jsx
import { useState, useEffect } from 'react';
import { ocorrenciaService } from '../services/ocorrenciaService';
import './SLATimer.css';

function SLATimer({ ocorrenciaId, status }) {
  const [timer, setTimer] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Status que devem mostrar o timer
  const statusComTimer = ['ABERTA', 'DESPACHADA', 'EM_ATENDIMENTO', 'CONCLUIDA'];

  useEffect(() => {
    if (!ocorrenciaId || !statusComTimer.includes(status)) {
      setLoading(false);
      return;
    }

    let interval = null;
    let isMounted = true;
    let retornouBase = false; // Flag para controlar se já retornou

    const carregarTimer = async () => {
      // Se já retornou, não atualizar mais
      if (retornouBase) {
        return;
      }

      try {
        const dados = await ocorrenciaService.obterTimer(ocorrenciaId);
        if (!isMounted) return;
        
        // Se retornou à base, marcar flag e parar o intervalo IMEDIATAMENTE
        if (dados && dados.retornouBase === true) {
          retornouBase = true;
          if (interval) {
            clearInterval(interval);
            interval = null;
          }
          setTimer(dados); // Manter os dados finais
          setError(null);
          setLoading(false);
          return; // Não continuar atualizando
        }
        
        setTimer(dados);
        setError(null);
      } catch (err) {
        if (!isMounted) return;
        setError(err.message);
      } finally {
        if (isMounted && !retornouBase) {
          setLoading(false);
        }
      }
    };

    // Carregar inicialmente e verificar se já retornou
    ocorrenciaService.obterTimer(ocorrenciaId).then(dados => {
      if (!isMounted) return;
      
      // Verificar se já retornou no carregamento inicial
      if (dados && dados.retornouBase === true) {
        retornouBase = true;
        setTimer(dados);
        setError(null);
        setLoading(false);
        // Não iniciar intervalo se já retornou
        return;
      }
      
      setTimer(dados);
      setError(null);
      setLoading(false);
      
      // Só iniciar intervalo se ainda não retornou e status não for CONCLUIDA
      if (dados && dados.retornouBase !== true && status !== 'CONCLUIDA') {
        interval = setInterval(carregarTimer, 2000);
      }
    }).catch(err => {
      if (!isMounted) return;
      setError(err.message);
      setLoading(false);
    });

    return () => {
      isMounted = false;
      if (interval) {
        clearInterval(interval);
      }
    };
  }, [ocorrenciaId, status]);

  if (!ocorrenciaId || !statusComTimer.includes(status)) {
    return null;
  }

  if (loading) {
    return (
      <div className="sla-timer-container">
        <div className="sla-loading">Carregando timer...</div>
      </div>
    );
  }

  if (error || !timer) {
    return null;
  }

  const getSlaStatusClass = () => {
    if (timer.slaExcedido) return 'sla-excedido';
    if (timer.slaEmRisco) return 'sla-risco';
    return 'sla-ok';
  };

  const getSlaStatusText = () => {
    if (timer.slaExcedido) return 'SLA Excedido';
    if (timer.slaEmRisco) return 'SLA em Risco';
    return 'SLA OK';
  };

  const calcularPercentualSla = () => {
    if (!timer.slaMinutos || timer.slaMinutos === 0) return 0;
    const percentual = ((timer.tempoSlaDecorridoMinutos || 0) / timer.slaMinutos) * 100;
    return Math.min(100, Math.max(0, percentual));
  };

  const calcularEtapasProgresso = () => {
    if (!timer.slaMinutos || timer.slaMinutos === 0) {
      return { ateDespacho: 0, ateChegada: 0, retorno: 0, total: 0 };
    }

    const slaTotalMinutos = timer.slaMinutos;
    let ateDespachoPercentual = 0;
    let ateChegadaPercentual = 0;
    let retornoPercentual = 0;

    // Calcular tempo até despacho (desde abertura até despacho)
    if (timer.foiDespachada && timer.dataHoraDespacho && timer.dataHoraAbertura) {
      try {
        const tempoAteDespachoSegundos = (new Date(timer.dataHoraDespacho) - new Date(timer.dataHoraAbertura)) / 1000;
        const tempoAteDespachoMinutos = tempoAteDespachoSegundos / 60;
        ateDespachoPercentual = (tempoAteDespachoMinutos / slaTotalMinutos) * 100;
      } catch (e) {
        ateDespachoPercentual = 0;
      }
    }

    // Calcular tempo de ida (despacho até chegada)
    if (timer.tempoAteChegadaMinutos !== null && timer.tempoAteChegadaMinutos !== undefined) {
      ateChegadaPercentual = (timer.tempoAteChegadaMinutos / slaTotalMinutos) * 100;
    }

    // Calcular tempo de retorno (apenas se OS está finalizada)
    if (timer.foiConcluida && timer.tempoRetornoDecorridoMinutos !== null && timer.tempoRetornoDecorridoMinutos !== undefined) {
      retornoPercentual = (timer.tempoRetornoDecorridoMinutos / slaTotalMinutos) * 100;
    }

    // Calcular o total usado do SLA (apenas tempo até chegada, sem retorno)
    const tempoSlaUsado = (timer.tempoSlaDecorridoMinutos || 0);
    const totalPercentual = (tempoSlaUsado / slaTotalMinutos) * 100;

    // Normalizar para que a soma das etapas visíveis não exceda o total
    const tempoAteChegadaTotal = ateDespachoPercentual + ateChegadaPercentual;

    // Se o tempo usado é diferente do esperado, ajustar proporcionalmente
    if (tempoAteChegadaTotal > 0 && totalPercentual > 0) {
      const fatorAjuste = Math.min(1, totalPercentual / tempoAteChegadaTotal);
      ateDespachoPercentual *= fatorAjuste;
      ateChegadaPercentual *= fatorAjuste;
    }

    return {
      ateDespacho: Math.min(100, Math.max(0, ateDespachoPercentual)),
      ateChegada: Math.min(100, Math.max(0, ateChegadaPercentual)),
      retorno: Math.min(100, Math.max(0, retornoPercentual)),
      total: Math.min(100, Math.max(0, totalPercentual))
    };
  };

  const percentual = calcularPercentualSla();
  const etapas = calcularEtapasProgresso();

  return (
    <div className={`sla-timer-container ${getSlaStatusClass()}`}>
      <div className="sla-header">
        <div className="sla-status-badge">
          <span className="sla-status-icon">
            {timer.slaExcedido ? '⚠️' : timer.slaEmRisco ? '⏱️' : '✅'}
          </span>
          <span className="sla-status-text">{getSlaStatusText()}</span>
        </div>
        <div className="sla-tempo-restante">
          {timer.tempoRestanteFormatado || '--'}
        </div>
      </div>
      
      <div className="sla-progress-bar-container">
        <div className="sla-progress-segmented">
          {/* Etapa 1: Tempo até despacho */}
          {etapas.ateDespacho > 0 && (
            <div 
              className="sla-progress-segment sla-segment-ate-despacho"
              style={{ width: `${Math.max(1, etapas.ateDespacho)}%` }}
              title="Tempo desde abertura até despacho"
            />
          )}
          {/* Etapa 2: Tempo de deslocamento (despacho até chegada) */}
          {etapas.ateChegada > 0 && (
            <div 
              className="sla-progress-segment sla-segment-ida"
              style={{ width: `${Math.max(1, etapas.ateChegada)}%` }}
              title="Tempo de deslocamento: base → destino"
            />
          )}
          {/* Etapa 3: Tempo de retorno (apenas se OS está finalizada) */}
          {timer.foiConcluida && etapas.retorno > 0 && (
            <div 
              className="sla-progress-segment sla-segment-retorno"
              style={{ width: `${Math.max(1, etapas.retorno)}%` }}
              title="Tempo de retorno à base (não conta para SLA)"
            />
          )}
          {/* Barra de fundo mostrando progresso total do SLA */}
          {percentual > 0 && (
            <div 
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: `${Math.min(100, percentual)}%`,
                height: '100%',
                backgroundColor: timer.slaExcedido ? '#dc3545' : timer.slaEmRisco ? '#ffc107' : '#10b981',
                opacity: 0.15,
                zIndex: 0,
                borderRadius: '10px'
              }}
            />
          )}
        </div>
        <div className="sla-progress-text">
          {timer.slaMinutos ? `${percentual.toFixed(1)}% do SLA utilizado` : 'Aguardando SLA...'}
        </div>
        <div className="sla-progress-legend">
          {etapas.ateDespacho > 0 && (
            <span className="sla-legend-item">
              <span className="sla-legend-color sla-legend-ate-despacho"></span>
              Até Despacho
            </span>
          )}
          {etapas.ateChegada > 0 && (
            <span className="sla-legend-item">
              <span className="sla-legend-color sla-legend-ida"></span>
              Deslocamento
            </span>
          )}
          {timer.foiConcluida && etapas.retorno > 0 && (
            <span className="sla-legend-item">
              <span className="sla-legend-color sla-legend-retorno"></span>
              Retorno (não conta para SLA)
            </span>
          )}
        </div>
      </div>

      <div className="sla-detalhes">
        <div className="sla-detalhe-item">
          <span className="sla-detalhe-label">Tempo Total:</span>
          <span className="sla-detalhe-valor">{timer.tempoTotalFormatado || '--'}</span>
        </div>
        {timer.tempoRestanteAteChegadaMinutos !== null && timer.tempoRestanteAteChegadaMinutos !== undefined && !timer.chegouLocal && (
          <div className="sla-detalhe-item">
            <span className="sla-detalhe-label">Tempo Restante até Chegada:</span>
            <span className="sla-detalhe-valor" style={{ 
              color: timer.tempoRestanteAteChegadaMinutos <= 0 ? '#dc3545' : '#28a745',
              fontWeight: 'bold'
            }}>
              {timer.tempoRestanteAteChegadaMinutos > 0 ? `${timer.tempoRestanteAteChegadaMinutos}m` : 'Chegou!'}
            </span>
          </div>
        )}
        {timer.tempoAteChegadaMinutos !== null && timer.chegouLocal && (
          <div className="sla-detalhe-item">
            <span className="sla-detalhe-label">Tempo até Chegada:</span>
            <span className="sla-detalhe-valor">
              {timer.tempoAteChegadaMinutos !== null ? `${timer.tempoAteChegadaMinutos}m` : '--'}
            </span>
          </div>
        )}
        {timer.distanciaKm !== null && timer.distanciaKm !== undefined && (
          <div className="sla-detalhe-item">
            <span className="sla-detalhe-label">Distância:</span>
            <span className="sla-detalhe-valor">
              {timer.distanciaKm.toFixed(2)} km
            </span>
          </div>
        )}
        {timer.slaMinutos && (
          <div className="sla-detalhe-item">
            <span className="sla-detalhe-label">SLA Total:</span>
            <span className="sla-detalhe-valor">{timer.slaMinutos}m</span>
          </div>
        )}
        {timer.foiConcluida && (
          <>
            {timer.retornouBase ? (
              <div className="sla-detalhe-item">
                <span className="sla-detalhe-label">Tempo Retorno:</span>
                <span className="sla-detalhe-valor" style={{ color: '#28a745' }}>
                  {timer.tempoRetornoDecorridoMinutos !== null ? `${timer.tempoRetornoDecorridoMinutos}m` : '--'} ✅
                </span>
              </div>
            ) : (
              <div className="sla-detalhe-item">
                <span className="sla-detalhe-label">Tempo Restante Retorno:</span>
                <span className="sla-detalhe-valor" style={{ 
                  color: '#ffc107',
                  fontWeight: 'bold'
                }}>
                  {timer.tempoRetornoMinutos !== null && timer.tempoRetornoDecorridoMinutos !== null 
                    ? `${Math.max(0, timer.tempoRetornoMinutos - timer.tempoRetornoDecorridoMinutos)}m` 
                    : '--'} (em andamento)
                </span>
              </div>
            )}
            {timer.retornouBase && (
              <div className="sla-detalhe-item">
                <span className="sla-detalhe-label">Status:</span>
                <span className="sla-detalhe-valor" style={{ color: '#28a745', fontWeight: 'bold' }}>
                  Ambulância e equipe disponíveis ✅
                </span>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}

export default SLATimer;
