// LifeTrack/frontend-react-legacy/src/pages/admin/sections/GerenciarUsuarios.jsx
import { useState, useEffect } from 'react';
import { usuarioService } from '../../../services/usuarioService';
import '../AdminDashboard.css';

function GerenciarUsuarios() {
  const [usuarios, setUsuarios] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [editingUsuario, setEditingUsuario] = useState(null);
  const [formData, setFormData] = useState({
    username: '',
    password: '',
    nome: '',
    email: '',
    telefone: '',
  });

  useEffect(() => {
    carregarUsuarios();
  }, []);

  const carregarUsuarios = async () => {
    try {
      setLoading(true);
      const data = await usuarioService.listar();
      setUsuarios(data);
      setError('');
    } catch (err) {
      setError('Erro ao carregar usuários: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleOpenModal = (usuario = null) => {
    if (usuario) {
      setEditingUsuario(usuario);
      setFormData({
        username: usuario.username,
        password: '',
        nome: usuario.nome,
        email: usuario.email,
        telefone: usuario.telefone || '',
      });
    } else {
      setEditingUsuario(null);
      setFormData({
        username: '',
        password: '',
        nome: '',
        email: '',
        telefone: '',
      });
    }
    setShowModal(true);
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setEditingUsuario(null);
    setFormData({
      username: '',
      password: '',
      nome: '',
      email: '',
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      setError('');
      
      if (editingUsuario) {
        await usuarioService.atualizarUsuario(editingUsuario.id, formData);
      } else {
        if (!formData.password) {
          setError('Senha é obrigatória para novos usuários');
          return;
        }
        await usuarioService.criarUsuario(formData);
      }
      
      handleCloseModal();
      carregarUsuarios();
    } catch (err) {
      setError('Erro ao salvar usuário: ' + err.message);
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Tem certeza que deseja deletar este usuário?')) {
      return;
    }

    try {
      await usuarioService.deletarUsuario(id);
      carregarUsuarios();
    } catch (err) {
      setError('Erro ao deletar usuário: ' + err.message);
    }
  };

  const handleToggleStatus = async (id) => {
    try {
      await usuarioService.toggleStatusUsuario(id);
      carregarUsuarios();
    } catch (err) {
      setError('Erro ao alterar status: ' + err.message);
    }
  };


  return (
    <div className="admin-dashboard">
      <div className="dashboard-header">
        <h1>Gerenciamento de Usuários</h1>
        <button className="btn-primary" onClick={() => handleOpenModal()}>
          + Novo Usuário
        </button>
      </div>

      {error && <div className="error-banner">{error}</div>}

      {loading ? (
        <div className="loading">Carregando usuários...</div>
      ) : (
        <div className="usuarios-table-container">
          <table className="usuarios-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Usuário</th>
                <th>Nome</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Roles</th>
                <th>Status</th>
                <th>Ações</th>
              </tr>
            </thead>
            <tbody>
              {usuarios.length === 0 ? (
                <tr>
                  <td colSpan="8" className="empty-message">
                    Nenhum usuário cadastrado
                  </td>
                </tr>
              ) : (
                usuarios.map((usuario) => (
                  <tr key={usuario.id}>
                    <td>{usuario.id}</td>
                    <td>{usuario.username}</td>
                    <td>{usuario.nome}</td>
                    <td>{usuario.email}</td>
                    <td>{usuario.telefone || '-'}</td>
                    <td>
                      <span className="role-badge">
                        {usuario.roles && usuario.roles.length > 0 
                          ? Array.from(usuario.roles).join(', ') 
                          : 'USER'}
                      </span>
                    </td>
                    <td>
                      <span className={`status-badge ${usuario.ativo ? 'ativo' : 'inativo'}`}>
                        {usuario.ativo ? 'Ativo' : 'Inativo'}
                      </span>
                    </td>
                    <td className="actions">
                      <button
                        className="btn-edit"
                        onClick={() => handleOpenModal(usuario)}
                      >
                        Editar
                      </button>
                      <button
                        className={`btn-toggle ${usuario.ativo ? 'desativar' : 'ativar'}`}
                        onClick={() => handleToggleStatus(usuario.id)}
                      >
                        {usuario.ativo ? 'Desativar' : 'Ativar'}
                      </button>
                      <button
                        className="btn-delete"
                        onClick={() => handleDelete(usuario.id)}
                      >
                        Deletar
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      )}

      {showModal && (
        <div className="modal-overlay" onClick={handleCloseModal}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h2>{editingUsuario ? 'Editar Usuário' : 'Novo Usuário'}</h2>
              <button className="btn-close" onClick={handleCloseModal}>×</button>
            </div>
            <form onSubmit={handleSubmit}>
              <div className="form-group">
                <label>Usuário *</label>
                <input
                  type="text"
                  value={formData.username}
                  onChange={(e) => setFormData({ ...formData, username: e.target.value })}
                  required
                />
              </div>
              <div className="form-group">
                <label>Senha {editingUsuario ? '(deixe em branco para manter)' : '*'}</label>
                <input
                  type="password"
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  required={!editingUsuario}
                />
              </div>
              <div className="form-group">
                <label>Nome Completo *</label>
                <input
                  type="text"
                  value={formData.nome}
                  onChange={(e) => setFormData({ ...formData, nome: e.target.value })}
                  required
                />
              </div>
              <div className="form-group">
                <label>Email *</label>
                <input
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  required
                />
              </div>
              <div className="form-group">
                <label>Telefone *</label>
                <input
                  type="tel"
                  value={formData.telefone}
                  onChange={(e) => setFormData({ ...formData, telefone: e.target.value })}
                  required
                  placeholder="(00) 00000-0000"
                />
              </div>
              {error && <div className="form-error">{error}</div>}
              <div className="modal-actions">
                <button type="button" className="btn-secondary" onClick={handleCloseModal}>
                  Cancelar
                </button>
                <button type="submit" className="btn-primary">
                  {editingUsuario ? 'Atualizar' : 'Criar'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}

export default GerenciarUsuarios;

// LifeTrack/frontend/src/app/pages/admin/gerenciar-usuarios/gerenciar-usuarios.component.ts
import { ChangeDetectorRef, Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { finalize } from 'rxjs';
import { UsuarioService } from '../../../core/services/usuario.service';
import { renderChanges } from '../../../core/utils/render-changes';

@Component({
  selector: 'app-gerenciar-usuarios',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './gerenciar-usuarios.component.html',
  styleUrls: ['../admin.shared.css']
})
export class GerenciarUsuariosComponent implements OnInit {
  usuarios: any[] = [];
  loading = true;
  error = '';
  showModal = false;
  editingUsuario: any = null;

  formData = { username: '', password: '', nome: '', email: '', telefone: '' };

  private usuarioService = inject(UsuarioService);
  private cdr = inject(ChangeDetectorRef);

  ngOnInit() { this.carregarUsuarios(); }

  carregarUsuarios() {
    this.loading = true;
    this.usuarioService.listar().pipe(
      finalize(() => renderChanges(this.cdr))
    ).subscribe({
      next: (d) => { this.usuarios = d; this.error = ''; this.loading = false; },
      error: (e) => { this.error = 'Erro ao carregar usuários: ' + (e.message || e); this.loading = false; }
    });
  }

  openModal(usuario: any = null) {
    this.editingUsuario = usuario;
    this.formData = usuario
      ? { username: usuario.username, password: '', nome: usuario.nome, email: usuario.email, telefone: usuario.telefone || '' }
      : { username: '', password: '', nome: '', email: '', telefone: '' };
    this.error = '';
    this.showModal = true;
  }

  closeModal() { this.showModal = false; this.editingUsuario = null; }

  handleSubmit() {
    this.error = '';
    if (!this.editingUsuario && !this.formData.password) {
      this.error = 'Senha é obrigatória para novos usuários';
      return;
    }
    const obs = this.editingUsuario
      ? this.usuarioService.atualizarUsuario(this.editingUsuario.id, this.formData)
      : this.usuarioService.criarUsuario(this.formData);
    obs.subscribe({
      next: () => { this.closeModal(); this.carregarUsuarios(); },
      error: (e) => { this.error = 'Erro ao salvar: ' + (e.error?.message || e.message); }
    });
  }

  handleDelete(id: number) {
    if (!window.confirm('Tem certeza que deseja deletar este usuário?')) return;
    this.usuarioService.deletarUsuario(id).subscribe({
      next: () => this.carregarUsuarios(),
      error: (e) => { this.error = 'Erro ao deletar: ' + (e.error?.message || e.message); }
    });
  }

  handleToggleStatus(id: number) {
    this.usuarioService.toggleStatusUsuario(id).subscribe({
      next: () => this.carregarUsuarios(),
      error: (e) => { this.error = 'Erro ao alterar status: ' + (e.error?.message || e.message); }
    });
  }

  rolesText(usuario: any): string {
    return usuario.roles?.length > 0 ? Array.from(usuario.roles as string[]).join(', ') : 'USER';
  }
}

<div class="admin-page">
  <div class="page-header">
    <h1 class="page-title">Gerenciamento de Usuários</h1>
    <button class="btn btn-primary" (click)="openModal()">+ Novo Usuário</button>
  </div>

  <div *ngIf="pageError" class="alert alert-error">{{ pageError }}</div>
  <div *ngIf="loading" class="loading-box">Carregando usuários...</div>

  <div *ngIf="!loading" class="table-card">
    <div class="table-wrapper">
      <table class="data-table">
        <thead><tr>
          <th>ID</th><th>Usuário</th><th>Nome</th><th>Email</th>
          <th>Telefone</th><th>Roles</th><th>Status</th><th>Ações</th>
        </tr></thead>
        <tbody>
          <tr *ngIf="usuarios.length === 0"><td colspan="8" style="text-align:center;padding:40px;color:#6b7280">Nenhum usuário cadastrado</td></tr>
          <tr *ngFor="let u of usuarios">
            <td class="text-muted">{{ u.id }}</td>
            <td>{{ u.username }}</td>
            <td>{{ u.nome }}</td>
            <td>{{ u.email }}</td>
            <td>{{ u.telefone || '-' }}</td>
            <td><span class="badge badge-info">{{ rolesText(u) }}</span></td>
            <td>
              <span class="badge" [class.badge-ativo]="u.ativo" [class.badge-inativo]="!u.ativo">
                {{ u.ativo ? 'Ativo' : 'Inativo' }}
              </span>
            </td>
            <td>
              <div class="actions-cell">
                <button class="btn btn-sm btn-secondary" (click)="openModal(u)">Editar</button>
                <button class="btn btn-sm" [class.btn-danger]="u.ativo" [class.btn-success]="!u.ativo" (click)="handleToggleStatus(u.id)">
                  {{ u.ativo ? 'Desativar' : 'Ativar' }}
                </button>
                <button class="btn btn-sm btn-danger" (click)="handleDelete(u.id)">Deletar</button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div *ngIf="showModal" class="modal-overlay" (click)="closeModal()">
  <div class="modal-box" (click)="$event.stopPropagation()">
    <div class="modal-header">
      <h2>{{ editingUsuario ? 'Editar Usuário' : 'Novo Usuário' }}</h2>
      <button class="btn-close-icon" (click)="closeModal()">×</button>
    </div>
    <form (ngSubmit)="handleSubmit()">
      <div class="form-group">
        <label class="form-label">Usuário *</label>
        <input class="form-input" type="text" [(ngModel)]="formData.username" name="username" required />
      </div>
      <div class="form-group">
        <label class="form-label">Senha {{ editingUsuario ? '(deixe em branco para manter)' : '*' }}</label>
        <input class="form-input" type="password" [(ngModel)]="formData.password" name="password" [required]="!editingUsuario" />
      </div>
      <div class="form-group">
        <label class="form-label">Nome Completo *</label>
        <input class="form-input" type="text" [(ngModel)]="formData.nome" name="nome" required />
      </div>
      <div class="form-group">
        <label class="form-label">Email *</label>
        <input class="form-input" type="email" [(ngModel)]="formData.email" name="email" required />
      </div>
      <div class="form-group">
        <label class="form-label">Telefone *</label>
        <input class="form-input" type="tel" [(ngModel)]="formData.telefone" name="telefone" placeholder="(00) 00000-0000" required />
      </div>
      <div *ngIf="modalError" class="form-error">{{ modalError }}</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" (click)="closeModal()">Cancelar</button>
        <button type="submit" class="btn btn-primary">{{ editingUsuario ? 'Atualizar' : 'Criar' }}</button>
      </div>
    </form>
  </div>
</div>
