// LifeTrack/frontend/src/app/shared/components/autocomplete-select/autocomplete-select.component.ts
import { Component, Input, Output, EventEmitter, forwardRef, ElementRef, ViewChild, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ControlValueAccessor, NG_VALUE_ACCESSOR, FormsModule } from '@angular/forms';

@Component({
  selector: 'app-autocomplete-select',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './autocomplete-select.component.html',
  styleUrls: ['./autocomplete-select.component.css'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => AutocompleteSelectComponent),
      multi: true
    }
  ]
})
export class AutocompleteSelectComponent implements ControlValueAccessor {
  @Input() options: any[] = [];
  @Input() placeholder: string = "Digite ou selecione...";
  @Input() required: boolean = false;
  
  @Input() getOptionLabel: (opt: any) => string = (opt) => opt?.label || opt?.nome || String(opt);
  @Input() getOptionValue: (opt: any) => any = (opt) => opt?.value || opt?.id || opt;

  @Output() valueChange = new EventEmitter<any>();

  isOpen: boolean = false;
  searchTerm: string = '';
  highlightedIndex: number = -1;
  innerValue: any = '';

  @ViewChild('inputRef') inputRef!: ElementRef<HTMLInputElement>;
  @ViewChild('containerRef') containerRef!: ElementRef<HTMLDivElement>;

  // Form Control callbacks
  onChange: any = () => {};
  onTouched: any = () => {};

  @HostListener('document:mousedown', ['$event'])
  onClickOutside(event: Event) {
    if (this.containerRef?.nativeElement && !this.containerRef.nativeElement.contains(event.target as Node)) {
      this.isOpen = false;
    }
  }

  get filteredOptions(): any[] {
    if (!this.searchTerm) return this.options;
    const term = this.searchTerm.toLowerCase();
    return this.options.filter(opt => 
      this.getOptionLabel(opt).toLowerCase().includes(term)
    );
  }

  // ControlValueAccessor methods
  writeValue(value: any): void {
    this.innerValue = value;
    this.updateSearchTermFromValue(value);
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  setDisabledState?(isDisabled: boolean): void {
    // Implement if necessary
  }

  private updateSearchTermFromValue(value: any) {
    if (value !== undefined && value !== null && value !== '') {
      const selectedOpt = this.options.find(opt => String(this.getOptionValue(opt)) === String(value));
      if (selectedOpt) {
        this.searchTerm = this.getOptionLabel(selectedOpt);
      } else {
        this.searchTerm = '';
      }
    } else {
      this.searchTerm = '';
    }
  }

  handleInputChange(event: any) {
    const term = event.target.value;
    this.searchTerm = term;
    this.isOpen = true;
    this.highlightedIndex = -1;

    const exactMatch = this.options.find(opt => 
      this.getOptionLabel(opt).toLowerCase() === term.toLowerCase()
    );

    if (exactMatch) {
      this.emitValue(this.getOptionValue(exactMatch));
    } else if (term === '') {
      this.emitValue('');
    }
  }

  handleFocus() {
    this.isOpen = true;
  }

  handleSelect(option: any) {
    const optionValue = this.getOptionValue(option);
    const optionLabel = this.getOptionLabel(option);
    
    this.emitValue(optionValue);
    this.searchTerm = optionLabel;
    this.isOpen = false;
    
    if (this.inputRef) {
      this.inputRef.nativeElement.blur();
    }
  }

  private emitValue(value: any) {
    this.innerValue = value;
    this.onChange(value);
    this.valueChange.emit(value);
  }

  handleKeyDown(event: KeyboardEvent) {
    if (!this.isOpen && (event.key === 'ArrowDown' || event.key === 'Enter')) {
      this.isOpen = true;
      return;
    }

    const filtered = this.filteredOptions;

    if (event.key === 'ArrowDown') {
      event.preventDefault();
      this.highlightedIndex = this.highlightedIndex < filtered.length - 1 ? this.highlightedIndex + 1 : this.highlightedIndex;
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      this.highlightedIndex = this.highlightedIndex > 0 ? this.highlightedIndex - 1 : -1;
    } else if (event.key === 'Enter' && this.highlightedIndex >= 0) {
      event.preventDefault();
      this.handleSelect(filtered[this.highlightedIndex]);
    } else if (event.key === 'Escape') {
      this.isOpen = false;
      if (this.inputRef) {
        this.inputRef.nativeElement.blur();
      }
    }
  }
}

<div #containerRef class="autocomplete-container">
  <input
    #inputRef
    type="text"
    [(ngModel)]="searchTerm"
    (input)="handleInputChange($event)"
    (focus)="handleFocus()"
    (keydown)="handleKeyDown($event)"
    (blur)="onTouched()"
    [placeholder]="placeholder"
    [required]="required"
    class="autocomplete-input"
  />
  
  <div *ngIf="isOpen && filteredOptions.length > 0" class="autocomplete-dropdown">
    <div
      *ngFor="let option of filteredOptions; let i = index"
      (click)="handleSelect(option)"
      (mouseenter)="highlightedIndex = i"
      class="autocomplete-option"
      [class.highlighted]="i === highlightedIndex"
      [class.selected]="getOptionValue(option) === innerValue"
    >
      {{ getOptionLabel(option) }}
    </div>
  </div>

  <div *ngIf="isOpen && filteredOptions.length === 0 && searchTerm" class="autocomplete-dropdown no-results">
    Nenhuma opção encontrada
  </div>
</div>

// LifeTrack/frontend-react-legacy/src/components/AutocompleteSelect.jsx
import { useState, useRef, useEffect } from 'react';

/**
 * Componente de select com autocomplete (permite digitação e seleção)
 */
function AutocompleteSelect({ 
  options, 
  value, 
  onChange, 
  placeholder = "Digite ou selecione...",
  getOptionLabel = (opt) => opt.label || opt.nome || opt,
  getOptionValue = (opt) => opt.value || opt.id || opt,
  required = false
}) {
  const [isOpen, setIsOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [highlightedIndex, setHighlightedIndex] = useState(-1);
  const containerRef = useRef(null);
  const inputRef = useRef(null);

  // Encontrar a opção selecionada
  const selectedOption = options.find(opt => {
    const optValue = getOptionValue(opt);
    return String(optValue) === String(value);
  });

  // Filtrar opções baseado no termo de busca
  const filteredOptions = options.filter(opt => {
    const label = getOptionLabel(opt).toLowerCase();
    return label.includes(searchTerm.toLowerCase());
  });

  // Atualizar searchTerm quando value mudar externamente
  useEffect(() => {
    if (value && value !== '' && selectedOption) {
      setSearchTerm(getOptionLabel(selectedOption));
    } else {
      setSearchTerm('');
    }
  }, [value]);

  // Fechar quando clicar fora
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (containerRef.current && !containerRef.current.contains(event.target)) {
        setIsOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleInputChange = (e) => {
    const term = e.target.value;
    setSearchTerm(term);
    setIsOpen(true);
    setHighlightedIndex(-1);

    // Se o termo corresponder exatamente a uma opção, selecionar
    const exactMatch = options.find(opt => 
      getOptionLabel(opt).toLowerCase() === term.toLowerCase()
    );
    if (exactMatch) {
      onChange(getOptionValue(exactMatch));
    } else if (term === '') {
      onChange('');
    }
  };

  const handleSelect = (option) => {
    const optionValue = getOptionValue(option);
    const optionLabel = getOptionLabel(option);
    onChange(optionValue);
    setSearchTerm(optionLabel);
    setIsOpen(false);
    inputRef.current?.blur();
  };

  const handleKeyDown = (e) => {
    if (!isOpen && (e.key === 'ArrowDown' || e.key === 'Enter')) {
      setIsOpen(true);
      return;
    }

    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setHighlightedIndex(prev => 
        prev < filteredOptions.length - 1 ? prev + 1 : prev
      );
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setHighlightedIndex(prev => prev > 0 ? prev - 1 : -1);
    } else if (e.key === 'Enter' && highlightedIndex >= 0) {
      e.preventDefault();
      handleSelect(filteredOptions[highlightedIndex]);
    } else if (e.key === 'Escape') {
      setIsOpen(false);
      inputRef.current?.blur();
    }
  };

  return (
    <div ref={containerRef} style={{ position: 'relative', width: '100%' }}>
      <input
        ref={inputRef}
        type="text"
        value={searchTerm}
        onChange={handleInputChange}
        onFocus={() => setIsOpen(true)}
        onKeyDown={handleKeyDown}
        placeholder={placeholder}
        required={required}
        style={{
          width: '100%',
          padding: '12px',
          border: '1px solid #d1d5db',
          borderRadius: '8px',
          fontSize: '1rem',
          boxSizing: 'border-box'
        }}
      />
      {isOpen && filteredOptions.length > 0 && (
        <div style={{
          position: 'absolute',
          top: '100%',
          left: 0,
          right: 0,
          backgroundColor: 'white',
          border: '1px solid #d1d5db',
          borderRadius: '8px',
          marginTop: '4px',
          maxHeight: '200px',
          overflowY: 'auto',
          zIndex: 1000,
          boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)'
        }}>
          {filteredOptions.map((option, index) => {
            const optionValue = getOptionValue(option);
            const optionLabel = getOptionLabel(option);
            const isHighlighted = index === highlightedIndex;
            const isSelected = optionValue === value;

            return (
              <div
                key={optionValue}
                onClick={() => handleSelect(option)}
                onMouseEnter={() => setHighlightedIndex(index)}
                style={{
                  padding: '12px',
                  cursor: 'pointer',
                  backgroundColor: isHighlighted 
                    ? '#f3f4f6' 
                    : isSelected 
                      ? '#e0e7ff' 
                      : 'white',
                  borderBottom: index < filteredOptions.length - 1 
                    ? '1px solid #e5e7eb' 
                    : 'none',
                  fontWeight: isSelected ? '600' : '400',
                  color: isSelected ? '#2563eb' : '#374151'
                }}
              >
                {optionLabel}
              </div>
            );
          })}
        </div>
      )}
      {isOpen && filteredOptions.length === 0 && searchTerm && (
        <div style={{
          position: 'absolute',
          top: '100%',
          left: 0,
          right: 0,
          backgroundColor: 'white',
          border: '1px solid #d1d5db',
          borderRadius: '8px',
          marginTop: '4px',
          padding: '12px',
          zIndex: 1000,
          boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
          color: '#6b7280'
        }}>
          Nenhuma opção encontrada
        </div>
      )}
    </div>
  );
}

export default AutocompleteSelect;
