// LifeTrack/frontend/src/app/shared/components/historico-ocorrencia/historico-ocorrencia.component.ts
import { Component, Input, OnInit, OnDestroy, OnChanges, SimpleChanges, inject } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { HistoricoService } from '../../../core/services/historico.service';

@Component({
  selector: 'app-historico-ocorrencia',
  standalone: true,
  imports: [CommonModule],
  providers: [DatePipe],
  templateUrl: './historico-ocorrencia.component.html',
  styleUrls: ['./historico-ocorrencia.component.css']
})
export class HistoricoOcorrenciaComponent implements OnInit, OnDestroy, OnChanges {
  @Input() ocorrenciaId!: number;
  @Input() atualizarEmTempoReal: boolean = false;

  historicos: any[] = [];
  loading: boolean = true;
  error: string | null = null;

  private historicoService = inject(HistoricoService);
  private datePipe = inject(DatePipe);

  ngOnInit() {
    this.iniciarBusca();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['ocorrenciaId'] || changes['atualizarEmTempoReal']) {
      this.iniciarBusca();
    }
  }

  ngOnDestroy() {
  }

  private iniciarBusca() {
    if (!this.ocorrenciaId) {
      this.loading = false;
      return;
    }

    this.carregarHistorico();
  }

  private carregarHistorico() {
    this.historicoService.buscarPorOcorrencia(this.ocorrenciaId).subscribe({
      next: (dados) => {
        this.historicos = dados;
        this.error = null;
        this.loading = false;
      },
      error: (err) => {
        this.error = err.message || 'Erro ao carregar histórico';
        this.loading = false;
      }
    });
  }

  formatarData(data: any): string {
    if (!data) return '-';
    return this.datePipe.transform(data, 'dd/MM/yyyy HH:mm:ss') || '-';
  }

  getAcaoIcon(acao: string): string {
    const icons: { [key: string]: string } = {
      'ABERTURA': '🆕',
      'DESPACHO': '🚑',
      'CHEGADA': '📍',
      'CONCLUSAO': '✅',
      'ALTERACAO_STATUS': '🔄',
      'CANCELAMENTO': '❌'
    };
    return icons[acao] || '📝';
  }

  getAcaoColor(acao: string): string {
    const colors: { [key: string]: string } = {
      'ABERTURA': '#17a2b8',
      'DESPACHO': '#007bff',
      'CHEGADA': '#28a745',
      'CONCLUSAO': '#6f42c1',
      'ALTERACAO_STATUS': '#ffc107',
      'CANCELAMENTO': '#dc3545'
    };
    return colors[acao] || '#6c757d';
  }
}

<div *ngIf="ocorrenciaId" class="historico-container">
  
  <div *ngIf="loading" class="historico-loading">
    Carregando histórico...
  </div>

  <div *ngIf="error" class="historico-error">
    Erro ao carregar histórico: {{ error }}
  </div>

  <div *ngIf="!loading && !error && historicos.length === 0" class="historico-empty">
    Nenhum histórico registrado ainda.
  </div>

  <ng-container *ngIf="!loading && !error && historicos.length > 0">
    <div class="historico-header">
      <h3>Histórico da Ocorrência</h3>
      <span *ngIf="atualizarEmTempoReal" class="historico-badge-live">🟢 Ao vivo</span>
    </div>
    
    <div class="historico-timeline">
      <div *ngFor="let historico of historicos" class="historico-item">
        <div class="historico-item-icon" [style.backgroundColor]="getAcaoColor(historico.acao)">
          {{ getAcaoIcon(historico.acao) }}
        </div>
        
        <div class="historico-item-content">
          <div class="historico-item-header">
            <span class="historico-acao" [style.color]="getAcaoColor(historico.acao)">
              {{ historico.acao }}
            </span>
            <span class="historico-data">{{ formatarData(historico.dataHora) }}</span>
          </div>
          
          <div class="historico-item-body">
            <div *ngIf="historico.tipoOcorrencia" class="historico-info-row">
              <strong>Tipo:</strong> {{ historico.tipoOcorrencia }}
            </div>
            
            <div *ngIf="historico.placaAmbulancia" class="historico-info-row">
              <strong>Ambulância:</strong> {{ historico.placaAmbulancia }}
              <span *ngIf="historico.acaoAmbulancia" class="historico-acao-ambulancia"> - {{ historico.acaoAmbulancia }}</span>
            </div>
            
            <div *ngIf="historico.descricaoAcao" class="historico-descricao">
              {{ historico.descricaoAcao }}
            </div>
            
            <div *ngIf="historico.statusAnterior && historico.statusNovo" class="historico-status-change">
              <span class="status-badge status-anterior">{{ historico.statusAnterior }}</span>
              <span class="status-arrow">→</span>
              <span class="status-badge status-novo">{{ historico.statusNovo }}</span>
            </div>
            
            <div *ngIf="historico.usuarioNome" class="historico-usuario">
              Por: {{ historico.usuarioNome }} ({{ historico.usuarioPerfil }})
            </div>
          </div>
        </div>
      </div>
    </div>
  </ng-container>

</div>

// LifeTrack/frontend-react-legacy/src/components/HistoricoOcorrencia.jsx
import { useState, useEffect } from 'react';
import { historicoService } from '../services/historicoService';
import './HistoricoOcorrencia.css';

function HistoricoOcorrencia({ ocorrenciaId, atualizarEmTempoReal = true }) {
  const [historicos, setHistoricos] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!ocorrenciaId) {
      setLoading(false);
      return;
    }

    const carregarHistorico = async () => {
      try {
        // Preservar posição do scroll durante atualizações
        const scrollPosition = window.scrollY || document.documentElement.scrollTop;
        
        const dados = await historicoService.buscarPorOcorrencia(ocorrenciaId);
        setHistoricos(dados);
        setError(null);
        
        // Restaurar posição do scroll após atualização
        requestAnimationFrame(() => {
          if (Math.abs((window.scrollY || document.documentElement.scrollTop) - scrollPosition) > 10) {
            window.scrollTo({
              top: scrollPosition,
              behavior: 'auto'
            });
          }
        });
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    carregarHistorico();

    // Atualizar em tempo real se habilitado
    let interval = null;
    if (atualizarEmTempoReal) {
      interval = setInterval(carregarHistorico, 3000); // Atualizar a cada 3 segundos
    }

    return () => {
      if (interval) {
        clearInterval(interval);
      }
    };
  }, [ocorrenciaId, atualizarEmTempoReal]);

  if (!ocorrenciaId) {
    return null;
  }

  if (loading) {
    return (
      <div className="historico-container">
        <div className="historico-loading">Carregando histórico...</div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="historico-container">
        <div className="historico-error">Erro ao carregar histórico: {error}</div>
      </div>
    );
  }

  const formatarData = (data) => {
    if (!data) return '-';
    const date = new Date(data);
    return date.toLocaleString('pt-BR');
  };

  const getAcaoIcon = (acao) => {
    const icons = {
      'ABERTURA': '🆕',
      'DESPACHO': '🚑',
      'CHEGADA': '📍',
      'CONCLUSAO': '✅',
      'ALTERACAO_STATUS': '🔄',
      'CANCELAMENTO': '❌'
    };
    return icons[acao] || '📝';
  };

  const getAcaoColor = (acao) => {
    const colors = {
      'ABERTURA': '#17a2b8',
      'DESPACHO': '#007bff',
      'CHEGADA': '#28a745',
      'CONCLUSAO': '#6f42c1',
      'ALTERACAO_STATUS': '#ffc107',
      'CANCELAMENTO': '#dc3545'
    };
    return colors[acao] || '#6c757d';
  };

  if (historicos.length === 0) {
    return (
      <div className="historico-container">
        <div className="historico-empty">Nenhum histórico registrado ainda.</div>
      </div>
    );
  }

  return (
    <div className="historico-container">
      <div className="historico-header">
        <h3>Histórico da Ocorrência</h3>
        {atualizarEmTempoReal && (
          <span className="historico-badge-live">🟢 Ao vivo</span>
        )}
      </div>
      <div className="historico-timeline">
        {historicos.map((historico, index) => (
          <div key={historico.id} className="historico-item">
            <div className="historico-item-icon" style={{ backgroundColor: getAcaoColor(historico.acao) }}>
              {getAcaoIcon(historico.acao)}
            </div>
            <div className="historico-item-content">
              <div className="historico-item-header">
                <span className="historico-acao" style={{ color: getAcaoColor(historico.acao) }}>
                  {historico.acao}
                </span>
                <span className="historico-data">{formatarData(historico.dataHora)}</span>
              </div>
              <div className="historico-item-body">
                {historico.tipoOcorrencia && (
                  <div className="historico-info-row">
                    <strong>Tipo:</strong> {historico.tipoOcorrencia}
                  </div>
                )}
                {historico.placaAmbulancia && (
                  <div className="historico-info-row">
                    <strong>Ambulância:</strong> {historico.placaAmbulancia}
                    {historico.acaoAmbulancia && (
                      <span className="historico-acao-ambulancia"> - {historico.acaoAmbulancia}</span>
                    )}
                  </div>
                )}
                {historico.descricaoAcao && (
                  <div className="historico-descricao">
                    {historico.descricaoAcao}
                  </div>
                )}
                {historico.statusAnterior && historico.statusNovo && (
                  <div className="historico-status-change">
                    <span className="status-badge status-anterior">{historico.statusAnterior}</span>
                    <span className="status-arrow">→</span>
                    <span className="status-badge status-novo">{historico.statusNovo}</span>
                  </div>
                )}
                {historico.usuarioNome && (
                  <div className="historico-usuario">
                    Por: {historico.usuarioNome} ({historico.usuarioPerfil})
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default HistoricoOcorrencia;
