// LifeTrack/frontend/src/pages/admin/AdminLayout.jsx
import { useState } from 'react';
import GerenciarUsuarios from './sections/GerenciarUsuarios';
import GerenciarEquipes from './sections/GerenciarEquipes';
import GerenciarFuncionarios from './sections/GerenciarFuncionarios';
import GerenciarAmbulancias from './sections/GerenciarAmbulancias';
import AnaliseEstrategica from './sections/AnaliseEstrategica';
import Relatorios from './sections/Relatorios';
import './AdminLayout.css';

function AdminLayout({ onLogout }) {
  const [activeSection, setActiveSection] = useState('usuarios');

  const menuItems = [
    { id: 'usuarios', label: 'Usuários', icon: '👥' },
    { id: 'equipes', label: 'Equipes', icon: '👨‍👩‍👧‍👦' },
    { id: 'funcionarios', label: 'Funcionários', icon: '👤' },
    { id: 'ambulancias', label: 'Ambulâncias', icon: '🚑' },
    { id: 'analise', label: 'Análise Estratégica', icon: '📊' },
    { id: 'relatorios', label: 'Relatórios', icon: '📈' },
  ];

  const handleLogout = () => {
    if (window.confirm('Deseja realmente sair?')) {
      if (onLogout) {
        onLogout();
      }
    }
  };

  const renderContent = () => {
    switch (activeSection) {
      case 'usuarios':
        return <GerenciarUsuarios />;
      case 'equipes':
        return <GerenciarEquipes />;
      case 'funcionarios':
        return <GerenciarFuncionarios />;
      case 'ambulancias':
        return <GerenciarAmbulancias />;
      case 'analise':
        return <AnaliseEstrategica />;
      case 'relatorios':
        return <Relatorios />;
      default:
        return <GerenciarUsuarios />;
    }
  };

  return (
    <div className="admin-layout">
      <aside className="admin-sidebar">
        <div className="sidebar-header">
          <h2>Painel Admin</h2>
        </div>
        <nav className="sidebar-nav">
          {menuItems.map((item) => (
            <button
              key={item.id}
              className={`nav-item ${activeSection === item.id ? 'active' : ''}`}
              onClick={() => setActiveSection(item.id)}
            >
              <span className="nav-icon">{item.icon}</span>
              <span className="nav-label">{item.label}</span>
            </button>
          ))}
        </nav>
        <div className="sidebar-footer">
          <button className="nav-item logout-btn" onClick={handleLogout}>
            <span className="nav-icon">🚪</span>
            <span className="nav-label">Sair</span>
          </button>
        </div>
      </aside>
      <main className="admin-content">
        {renderContent()}
      </main>
    </div>
  );
}

export default AdminLayout;

// LifeTrack/frontend-angular/src/app/layouts/admin-layout/admin-layout.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-admin-layout',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './admin-layout.component.html',
  styleUrls: ['./admin-layout.component.css']
})
export class AdminLayoutComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  menuItems = [
    { path: '/admin/usuarios', label: 'Usuários', icon: '👥' },
    { path: '/admin/equipes', label: 'Equipes', icon: '👨‍👩‍👧‍👦' },
    { path: '/admin/funcionarios', label: 'Funcionários', icon: '👤' },
    { path: '/admin/ambulancias', label: 'Ambulâncias', icon: '🚑' },
    { path: '/admin/analise', label: 'Análise Estratégica', icon: '📊' },
    { path: '/admin/relatorios', label: 'Relatórios', icon: '📈' },
  ];

  handleLogout() {
    if (window.confirm('Deseja realmente sair?')) {
      this.authService.logout();
      this.router.navigate(['/login']);
    }
  }
}

<div class="admin-layout">
  <aside class="admin-sidebar">
    <div class="sidebar-header">
      <h2>Painel Admin</h2>
    </div>
    <nav class="sidebar-nav">
      <a 
        *ngFor="let item of menuItems"
        [routerLink]="item.path"
        routerLinkActive="active"
        class="nav-item"
      >
        <span class="nav-icon">{{ item.icon }}</span>
        <span class="nav-label">{{ item.label }}</span>
      </a>
    </nav>
    <div class="sidebar-footer">
      <button class="nav-item logout-btn" (click)="handleLogout()">
        <span class="nav-icon">🚪</span>
        <span class="nav-label">Sair</span>
      </button>
    </div>
  </aside>
  <main class="admin-content">
    <router-outlet></router-outlet>
  </main>
</div>
